// The QuickUVM configuration actions (docs/03): setDut with explicitly
// confirmed heuristics, agent from a pin selection (with the perspective
// inversion!), agent from an interface (unfolding the modport), ignoring
// ports. All produce YAML edits through ConfigService.apply (WorkspaceEdit).

import * as path from "path";
import * as vscode from "vscode";
import {
  deriveConnections,
  parentComposition,
  planWireEdits,
  subenvMapping,
  subenvName,
} from "./compose";
import { ConfigService, TbEditTarget } from "./config";
// the name-based heuristics (including the _ni/_bi pitfall) live in heuristics (pure, tested)
import { ACTIVE_LOW_RE, CLOCK_RE, RESET_RE, SV_IDENT_RE } from "./heuristics";
import { Instance, ModuleDef, Port, ProjectModel } from "./model";
import { probeCoverageAllowed, proposeProbe } from "./probe";
import * as ops from "./yamlops";

export class Actions {
  constructor(
    private readonly getModel: () => ProjectModel | undefined,
    private readonly config: ConfigService,
    private readonly log: vscode.OutputChannel
  ) {}

  private resolve(
    viewId: string | undefined
  ): { inst: Instance; def: ModuleDef } | undefined {
    const model = this.getModel();
    const inst = model?.instances.find((i) => i.path === viewId);
    const def = inst ? model?.modules[inst.module] : undefined;
    if (!inst || !def) {
      void vscode.window.showWarningMessage(
        vscode.l10n.t(
          "QuickUVM Architect: open the symbol view of an instance first."
        )
      );
      return undefined;
    }
    return { inst, def };
  }

  // ------------------------------------------------------------- setDut

  /** Designating the DUT with heuristic proposals, never applied silently. */
  async setDut(viewId: string | undefined): Promise<void> {
    const r = this.resolve(viewId);
    if (!r) {
      return;
    }
    const { inst, def } = r;
    const oneBitIns = def.ports.filter((p) => p.dir === "in" && p.width === 1);
    let clock = oneBitIns.find((p) => CLOCK_RE.test(p.name))?.name ?? null;
    const reset = oneBitIns.find((p) => RESET_RE.test(p.name))?.name ?? null;

    type Item = vscode.QuickPickItem & { id: string };
    const items: Item[] = [];
    if (clock) {
      items.push({
        id: "clock",
        label: vscode.l10n.t("$(watch) Clock: {0}", clock),
        detail: vscode.l10n.t("heuristic — uncheck if this is not the clock"),
        picked: true,
      });
    } else {
      items.push({
        id: "comb",
        label: vscode.l10n.t(
          "$(circuit-board) Combinational DUT (no clock of its own)"
        ),
        detail: vscode.l10n.t(
          "no clock candidate found; the testbench cadence remains"
        ),
        picked: true,
      });
    }
    if (reset) {
      const low = ACTIVE_LOW_RE.test(reset);
      items.push({
        id: "reset",
        label: vscode.l10n.t(
          "$(refresh) Reset: {0} (active on {1})",
          reset,
          low ? "0" : "1"
        ),
        picked: true,
      });
      items.push({
        id: "external",
        label: vscode.l10n.t(
          "$(plug) External reset (generated by the testbench, not by the agent)"
        ),
        picked: false,
      });
    }
    const picked = await vscode.window.showQuickPick(items, {
      canPickMany: true,
      title: vscode.l10n.t("Set as DUT: {0}", inst.module),
      placeHolder: vscode.l10n.t("Confirm the heuristic proposals (docs/03)"),
    });
    if (!picked) {
      return;
    }
    const has = (id: string) => picked.some((i) => i.id === id);

    if (clock && !has("clock")) {
      clock = null;
    }
    let combinational = !clock && (has("comb") || !items.some((i) => i.id === "comb"));
    if (!clock && !has("comb") && items.some((i) => i.id === "comb")) {
      // the user refuses combinational too: choose the clock manually
      const pick = await vscode.window.showQuickPick(
        oneBitIns.map((p) => p.name),
        { title: vscode.l10n.t("Choose the clock port") }
      );
      if (!pick) {
        return;
      }
      clock = pick;
      combinational = false;
    }

    const spec: ops.DutSpec = {
      module: inst.module,
      clock,
      reset: has("reset") && reset ? reset : null,
      resetActiveLow: reset ? ACTIVE_LOW_RE.test(reset) : true,
      externalReset: has("external"),
      combinational,
    };
    // active config on a DIFFERENT dut: explicit choice — overwrite the dut of
    // the active config (phase 2 semantics) or create the config dedicated to
    // the block (the recursive composition flow, docs/03); nothing silent
    const activeDut = this.config.current.dut?.name;
    let uri: vscode.Uri | undefined;
    if (activeDut && activeDut !== inst.module && this.config.configUri) {
      const overwrite = vscode.l10n.t(
        "Change the DUT of the active config ({0} → {1})",
        activeDut,
        inst.module
      );
      const fresh = vscode.l10n.t(
        "Create {0}.quickuvm.yaml for this block (subenv child config)",
        inst.module
      );
      const pick = await vscode.window.showQuickPick([fresh, overwrite], {
        title: vscode.l10n.t("Set as DUT: {0}", inst.module),
        placeHolder: vscode.l10n.t(
          'The active config targets "{0}" — choose what to do',
          activeDut
        ),
      });
      if (!pick) {
        return;
      }
      uri =
        pick === fresh
          ? await this.config.createConfigFor(inst.module)
          : await this.config.ensureConfig(inst.module);
    } else {
      uri = await this.config.ensureConfig(inst.module);
    }
    if (!uri) {
      return;
    }
    if (await this.config.apply((t) => ops.setDut(t, spec))) {
      this.log.appendLine(`[actions] setDut ${inst.module} -> ${uri.fsPath}`);
    }
  }

  // ------------------------------------------------- agent from selection

  /**
   * Agent from the selected pins. The YAML directions are from the DUT's
   * perspective (docs/03): the DUT inputs become `inputs` (the agent drives them), the outputs
   * `outputs` with randomize: false.
   */
  async createAgentFromPins(
    viewId: string | undefined,
    pinIds: string[]
  ): Promise<void> {
    const r = this.resolve(viewId);
    if (!r) {
      return;
    }
    const { inst, def } = r;
    if (!(await this.ensureDutForView(inst))) {
      return;
    }
    const names = pinIds
      .map((id) => id.replace(/^<port>\./, ""))
      .filter((n, i, all) => all.indexOf(n) === i);
    const ports = names
      .map((n) => def.ports.find((p) => p.name === n))
      .filter((p): p is Port => Boolean(p));
    if (ports.length === 0) {
      void vscode.window.showWarningMessage(
        vscode.l10n.t(
          "QuickUVM Architect: select the DUT pins for the agent first."
        )
      );
      return;
    }

    const roles = this.config.lastOverlay?.roles ?? {};
    const inputs: ops.AgentPortSpec[] = [];
    const outputs: ops.AgentPortSpec[] = [];
    const skipped: string[] = [];

    for (const p of ports) {
      if (roles[p.name] === "clock" || roles[p.name] === "reset") {
        skipped.push(vscode.l10n.t("{0} (role {1})", p.name, roles[p.name]));
        continue;
      }
      if (p.dir === "inout" || p.dir === "ref") {
        skipped.push(
          vscode.l10n.t("{0} (inout not supported by the QuickUVM schema)", p.name)
        );
        continue;
      }
      if (p.width === null) {
        skipped.push(vscode.l10n.t("{0} (no fixed size)", p.name));
        continue;
      }
      let width = p.width;
      if (p.unpacked_dims) {
        // unpacked array: explicit decision per port (docs/03)
        const flat = vscode.l10n.t("Flatten (width={0})", p.width);
        const choice = await vscode.window.showQuickPick(
          [flat, vscode.l10n.t("Exclude the port")],
          {
            title: vscode.l10n.t(
              "\"{0}\" is an unpacked array {1} × {2} bits — QuickUVM has no such notion",
              p.name,
              JSON.stringify(p.unpacked_dims),
              String(p.elem_width)
            ),
          }
        );
        if (!choice) {
          return;
        }
        if (choice !== flat) {
          skipped.push(vscode.l10n.t("{0} (unpacked array excluded)", p.name));
          continue;
        }
        width = p.width;
      }
      (p.dir === "in" ? inputs : outputs).push({ name: p.name, width });
    }

    if (inputs.length + outputs.length === 0) {
      void vscode.window.showWarningMessage(
        vscode.l10n.t(
          "QuickUVM Architect: no usable pin in the selection ({0}).",
          skipped.join("; ")
        )
      );
      return;
    }

    const name = await this.askAgentName(suggestName(names));
    if (!name) {
      return;
    }
    const style = vscode.workspace
      .getConfiguration("quickuvm")
      .get<"manual" | "field_macros">("seqItemStyle", "manual");

    if (
      await this.config.apply((t) =>
        ops.createAgent(t, { name, inputs, outputs, seqItemStyle: style })
      )
    ) {
      const note = skipped.length
        ? vscode.l10n.t(" (excluded: {0})", skipped.join("; "))
        : "";
      void vscode.window.showInformationMessage(
        vscode.l10n.t(
          "QuickUVM Architect: agent \"{0}\" with {1} inputs / {2} outputs{3}.",
          name,
          inputs.length,
          outputs.length,
          note
        )
      );
    }
  }

  // ------------------------------------------------ agent from interface

  /** Agent from the interface port: unfolds the DUT's modport (docs/03). */
  async createAgentFromIface(
    viewId: string | undefined,
    portName: string
  ): Promise<void> {
    const model = this.getModel();
    const r = this.resolve(viewId);
    if (!r || !model) {
      return;
    }
    const { inst, def } = r;
    if (!(await this.ensureDutForView(inst))) {
      return;
    }
    const ifp = def.iface_ports.find((p) => p.name === portName);
    if (!ifp) {
      return;
    }

    // the connected interface instance: through the parent's view, otherwise by type
    const ifaceInst = this.connectedIface(model, inst, portName, ifp.interface);
    if (!ifaceInst?.iface) {
      void vscode.window.showWarningMessage(
        vscode.l10n.t(
          "QuickUVM Architect: cannot find an instance of interface \"{0}\" with elaborated signals.",
          ifp.interface
        )
      );
      return;
    }
    const modportName = ifp.modport ?? "";
    const modport = ifaceInst.iface.modports[modportName];
    if (!modport) {
      void vscode.window.showWarningMessage(
        vscode.l10n.t(
          "QuickUVM Architect: interface \"{0}\" has no modport \"{1}\" in the model.",
          ifp.interface,
          modportName
        )
      );
      return;
    }

    const widths = new Map(
      ifaceInst.iface.signals.map((s) => [s.name, s.width])
    );
    const inputs: ops.AgentPortSpec[] = [];
    const outputs: ops.AgentPortSpec[] = [];
    const skipped: string[] = [];
    for (const [signal, dir] of Object.entries(modport)) {
      const width = widths.get(signal) ?? null;
      if (CLOCK_RE.test(signal) && width === 1) {
        skipped.push(vscode.l10n.t("{0} (interface clock -> dut.clock)", signal));
        continue;
      }
      if (width === null) {
        skipped.push(vscode.l10n.t("{0} (no fixed size)", signal));
        continue;
      }
      // the same perspective inversion: an `in` signal in the DUT's modport
      // => the DUT receives it => the agent drives it => inputs
      if (dir === "in") {
        inputs.push({ name: signal, width });
      } else if (dir === "out") {
        outputs.push({ name: signal, width });
      } else {
        skipped.push(vscode.l10n.t("{0} ({1} not supported)", signal, dir));
      }
    }
    if (inputs.length + outputs.length === 0) {
      void vscode.window.showWarningMessage(
        vscode.l10n.t(
          "QuickUVM Architect: modport \"{0}\" has no usable signals ({1}).",
          modportName,
          skipped.join("; ")
        )
      );
      return;
    }

    const name = await this.askAgentName(portName);
    if (!name) {
      return;
    }
    const style = vscode.workspace
      .getConfiguration("quickuvm")
      .get<"manual" | "field_macros">("seqItemStyle", "manual");
    if (
      await this.config.apply((t) =>
        ops.createAgent(t, { name, inputs, outputs, seqItemStyle: style })
      )
    ) {
      const note = skipped.length
        ? vscode.l10n.t(" (excluded: {0})", skipped.join("; "))
        : "";
      void vscode.window.showInformationMessage(
        vscode.l10n.t(
          "QuickUVM Architect: agent \"{0}\" from {1}.{2}{3}. The original SV interface remains the source of the specification; QuickUVM generates its own {0}_if.sv (known limitation, docs/03).",
          name,
          ifp.interface,
          modportName,
          note
        )
      );
    }
  }

  // ------------------------------------------------------ createSubenv

  /**
   * H1 subenvs from the blocks selected in the schematic view (docs/03): one
   * subenv per instance (the folds are unfolded into members), the child's config
   * `<modul>.quickuvm.yaml` next to the top config, created when needed with a skeleton +
   * heuristic dut; params with integer values only (the schema requires dict[str, int]).
   * The QuickUVM H1 constraints (children combinational only; params require
   * `parameters:` declared in the block's agent) are flagged in the confirmation.
   */
  async createSubenv(
    viewId: string | undefined,
    nodeIds: string[]
  ): Promise<void> {
    const model = this.getModel();
    const r = this.resolve(viewId);
    if (!r || !model) {
      return;
    }
    const { inst } = r;
    if (!(await this.ensureDutForView(inst))) {
      return;
    }
    const topUri = this.config.configUri;
    if (!topUri) {
      return;
    }

    // the selection -> child instances: the folds are unfolded, the interfaces are skipped
    const rels = [...new Set(nodeIds.flatMap(expandFold))];
    const targets: { rel: string; child: Instance }[] = [];
    for (const rel of rels) {
      const child = model.instances.find(
        (i) => i.path === `${inst.path}.${rel}`
      );
      if (child && !child.iface) {
        targets.push({ rel, child });
      }
    }
    if (targets.length === 0) {
      void vscode.window.showWarningMessage(
        vscode.l10n.t(
          "QuickUVM Architect: select one or more child blocks in the schematic view first."
        )
      );
      return;
    }

    // proposals: unique names; the subenvs already present in YAML are skipped
    const existing = new Set(
      (this.config.current.subenvs ?? [])
        .map((s) => s.name)
        .filter((n): n is string => Boolean(n))
    );
    const used = new Set(existing);
    const already: string[] = [];
    interface Proposal {
      name: string;
      rel: string;
      module: string;
      configFile: string;
      params: Record<string, number>;
      skippedParams: string[];
    }
    const proposals: Proposal[] = [];
    for (const { rel, child } of targets) {
      const base = subenvName(rel);
      if (existing.has(base)) {
        already.push(rel);
        continue;
      }
      let name = base;
      for (let n = 2; used.has(name); n++) {
        name = `${base}_${n}`;
      }
      used.add(name);
      const params: Record<string, number> = {};
      const skippedParams: string[] = [];
      for (const [k, v] of Object.entries(child.params)) {
        if (/^-?\d+$/.test(v.trim())) {
          params[k] = Number(v.trim());
        } else {
          skippedParams.push(`${k}=${v}`);
        }
      }
      proposals.push({
        name,
        rel,
        module: child.module,
        configFile: `${child.module}.quickuvm.yaml`,
        params,
        skippedParams,
      });
    }
    if (proposals.length === 0) {
      void vscode.window.showInformationMessage(
        vscode.l10n.t(
          "QuickUVM Architect: the selected blocks are already subenvs ({0}).",
          already.join(", ")
        )
      );
      return;
    }

    // the missing child configs: skeleton + heuristic dut, summarized in the confirmation
    const dir = vscode.Uri.joinPath(topUri, "..");
    const newConfigs = new Map<string, { uri: vscode.Uri; spec: ops.DutSpec }>();
    for (const p of proposals) {
      if (newConfigs.has(p.module)) {
        continue;
      }
      const uri = vscode.Uri.joinPath(dir, p.configFile);
      try {
        await vscode.workspace.fs.stat(uri);
      } catch {
        newConfigs.set(p.module, {
          uri,
          spec: heuristicDut(p.module, this.getModel()?.modules[p.module]),
        });
      }
    }

    type Item = vscode.QuickPickItem & { proposal: Proposal };
    const items: Item[] = proposals.map((p) => {
      const fresh = newConfigs.get(p.module);
      const notes: string[] = [];
      if (Object.keys(p.params).length) {
        notes.push(
          `params: {${Object.entries(p.params)
            .map(([k, v]) => `${k}: ${v}`)
            .join(", ")}}`
        );
      }
      if (p.skippedParams.length) {
        notes.push(
          vscode.l10n.t("non-integer params omitted: {0}",
            p.skippedParams.join(", "))
        );
      }
      if (fresh) {
        // children with a clock are accepted by the H1 composition from the M1
        // clocked-subenv slice (single-clock, at most one reset) — the heuristic
        // skeleton always satisfies the condition
        notes.push(
          fresh.spec.combinational
            ? vscode.l10n.t("new config (combinational DUT)")
            : vscode.l10n.t(
                "new config (clock: {0}, reset: {1})",
                fresh.spec.clock ?? "?",
                fresh.spec.reset ?? "—"
              )
        );
      }
      return {
        proposal: p,
        label: p.name,
        description: `${p.module} → ${p.configFile}`,
        detail: notes.join(" • ") || undefined,
        picked: true,
      };
    });
    const picked = await vscode.window.showQuickPick(items, {
      canPickMany: true,
      title: vscode.l10n.t("Create subenvs in {0}", inst.module),
      placeHolder: vscode.l10n.t(
        "Confirm the subenvs to add (docs/03); params require the block agent to declare `parameters:`"
      ),
    });
    if (!picked || picked.length === 0) {
      return;
    }

    // 1. the missing child configs, only for the confirmed modules
    const chosenModules = new Set(picked.map((i) => i.proposal.module));
    const creations = [...newConfigs.entries()].filter(([m]) =>
      chosenModules.has(m)
    );
    if (creations.length) {
      const edit = new vscode.WorkspaceEdit();
      for (const [module, c] of creations) {
        edit.createFile(c.uri, {
          ignoreIfExists: true,
          contents: Buffer.from(
            ops.setDut(ops.newConfigText(module), c.spec),
            "utf8"
          ),
        });
      }
      await vscode.workspace.applyEdit(edit);
      for (const [, c] of creations) {
        this.log.appendLine(`[actions] createSubenv: created ${c.uri.fsPath}`);
      }
    }

    // hybrid guard: quick-uvm FORBIDS `subenvs` + own agents — if
    // the target config already has agents, the composition would make it invalid (generate would
    // fail). We confirm explicitly; the user can proceed (and remove the agents)
    if ((this.config.current.agents?.length ?? 0) > 0) {
      const PROCEED = vscode.l10n.t("Compose anyway");
      const pick = await vscode.window.showWarningMessage(
        vscode.l10n.t(
          'The config for "{0}" defines its own agents. QuickUVM rejects a bench that has both agents and subenvs — you will need to remove the agents. Compose anyway?',
          inst.module
        ),
        { modal: true },
        PROCEED
      );
      if (pick !== PROCEED) {
        return;
      }
    }

    // 2. the subenvs entries into the top config (a single WorkspaceEdit)
    const specs: ops.SubenvSpec[] = picked.map((i) => ({
      name: i.proposal.name,
      config: i.proposal.configFile,
      params: i.proposal.params,
    }));
    if (await this.config.apply((t) => ops.createSubenvs(t, specs))) {
      const notes: string[] = [];
      if (creations.length) {
        notes.push(
          vscode.l10n.t(
            "{0} new block config(s) — configure their agents next (recursive flow, docs/03)",
            creations.length
          )
        );
      }
      if (already.length) {
        notes.push(
          vscode.l10n.t("already subenvs: {0}", already.join(", "))
        );
      }
      void vscode.window.showInformationMessage(
        vscode.l10n.t(
          "QuickUVM Architect: {0} subenv(s) added{1}.",
          specs.length,
          notes.length ? ` (${notes.join("; ")})` : ""
        )
      );
    }
  }

  // ------------------------------------ the verification view (3b, slice 2)

  /** the names of the agents from the active config */
  private agentNames(cfg: TbEditTarget, activeOnly = false): string[] {
    return (cfg.current.agents ?? [])
      .filter((a) => !activeOnly || a.active !== false)
      .map((a) => a.name)
      .filter((n): n is string => Boolean(n));
  }

  /** a unique name for a new entry (`base`, then `base2`, `base3`…) */
  private static uniqueName(base: string, taken: Set<string>): string {
    if (!taken.has(base)) {
      return base;
    }
    for (let n = 2; ; n++) {
      const name = `${base}${n}`;
      if (!taken.has(name)) {
        return name;
      }
    }
  }

  /** Coverage collector for an agent (`analysis.coverage`, docs/03).
   *  `cfg` = the active config (panel) OR the open document (CustomTextEditor). */
  async addCoverage(preselect?: string, cfg: TbEditTarget = this.config): Promise<void> {
    if (!cfg.configUri) {
      return this.warnNoConfig();
    }
    const agents = this.agentNames(cfg);
    if (!agents.length) {
      return this.warnNoAgents();
    }
    const covered = new Set(cfg.current.analysis?.coverage ?? []);
    const choices = agents.filter((a) => !covered.has(a));
    if (!choices.length) {
      void vscode.window.showInformationMessage(
        vscode.l10n.t("QuickUVM Architect: every agent already has a coverage collector.")
      );
      return;
    }
    let agent = preselect && choices.includes(preselect) ? preselect : undefined;
    if (!agent) {
      agent = await vscode.window.showQuickPick(choices, {
        title: vscode.l10n.t("Coverage collector for agent"),
      });
      if (!agent) {
        return;
      }
    }
    const a = agent;
    if (await cfg.apply((t) => ops.addCoverage(t, a))) {
      this.log.appendLine(`[actions] addCoverage ${a}`);
    }
  }

  /** Scoreboard from the agents' streams (`analysis.scoreboards`, docs/03). */
  async addScoreboard(preselSource?: string, cfg: TbEditTarget = this.config): Promise<void> {
    if (!cfg.configUri) {
      return this.warnNoConfig();
    }
    const agents = this.agentNames(cfg);
    if (!agents.length) {
      return this.warnNoAgents();
    }
    let source =
      preselSource && agents.includes(preselSource) ? preselSource : undefined;
    if (!source) {
      source = await vscode.window.showQuickPick(agents, {
        title: vscode.l10n.t("Scoreboard: stimulus/source agent"),
        placeHolder: vscode.l10n.t("the stream fed into the predictor"),
      });
      if (!source) {
        return;
      }
    }
    const src = source;
    const NONE = vscode.l10n.t("$(circle-slash) None (single-stream)");
    const monPick = await vscode.window.showQuickPick(
      [NONE, ...agents.filter((a) => a !== src)],
      {
        title: vscode.l10n.t("Scoreboard: response/monitor agent (A2 two-stream)"),
        placeHolder: vscode.l10n.t("the observed stream compared against the prediction"),
      }
    );
    if (monPick === undefined) {
      return;
    }
    const monitor = monPick === NONE ? undefined : monPick;

    let match: "in_order" | "out_of_order" = "in_order";
    let matchKey: string | undefined;
    if (monitor) {
      const IN = vscode.l10n.t("In order (FIFO pair)");
      const OOO = vscode.l10n.t("Out of order (keyed pool — a reordering DUT)");
      const mPick = await vscode.window.showQuickPick([IN, OOO], {
        title: vscode.l10n.t("Scoreboard: comparison strategy"),
      });
      if (!mPick) {
        return;
      }
      if (mPick === OOO) {
        match = "out_of_order";
        matchKey = await vscode.window.showInputBox({
          title: vscode.l10n.t("Match key (monitor transaction field)"),
          prompt: vscode.l10n.t("the field each response is keyed on (required for out-of-order)"),
          validateInput: (v) =>
            SV_IDENT_RE.test(v)
              ? undefined
              : vscode.l10n.t("invalid SystemVerilog identifier"),
        });
        if (!matchKey) {
          return;
        }
      }
    }

    const taken = new Set(
      (cfg.current.analysis?.scoreboards ?? [])
        .map((s) => s.name)
        .filter((n): n is string => Boolean(n))
    );
    const name = await vscode.window.showInputBox({
      title: vscode.l10n.t("Scoreboard name"),
      value: Actions.uniqueName("sbd", taken),
      validateInput: (v) =>
        !SV_IDENT_RE.test(v)
          ? vscode.l10n.t("invalid SystemVerilog identifier")
          : taken.has(v)
            ? vscode.l10n.t("a scoreboard with this name already exists")
            : undefined,
    });
    if (!name) {
      return;
    }
    if (
      await cfg.apply((t) =>
        ops.addScoreboard(t, { name, source: src, monitor, match, matchKey })
      )
    ) {
      this.log.appendLine(
        `[actions] addScoreboard ${name} (${src}${monitor ? ` vs ${monitor}` : ""})`
      );
    }
  }

  /** Virtual sequence coordinating the sequencers of the active agents (C2, docs/03). */
  async addVirtualSequence(cfg: TbEditTarget = this.config): Promise<void> {
    if (!cfg.configUri) {
      return this.warnNoConfig();
    }
    const active = this.agentNames(cfg, true);
    if (!active.length) {
      void vscode.window.showWarningMessage(
        vscode.l10n.t("QuickUVM Architect: a virtual sequence needs at least one active agent.")
      );
      return;
    }
    const taken = new Set(
      (cfg.current.virtual_sequences ?? [])
        .map((v) => v.name)
        .filter((n): n is string => Boolean(n))
    );
    const name = await vscode.window.showInputBox({
      title: vscode.l10n.t("Virtual sequence name"),
      value: Actions.uniqueName("vseq", taken),
      validateInput: (v) =>
        !SV_IDENT_RE.test(v)
          ? vscode.l10n.t("invalid SystemVerilog identifier")
          : taken.has(v)
            ? vscode.l10n.t("a virtual sequence with this name already exists")
            : undefined,
    });
    if (!name) {
      return;
    }
    const picked =
      active.length === 1
        ? active
        : await vscode.window.showQuickPick(
            active.map((a) => ({ label: a, picked: true })),
            {
              canPickMany: true,
              title: vscode.l10n.t("Virtual sequence: agents to coordinate"),
            }
          ).then((sel) => sel?.map((i) => i.label));
    if (!picked || picked.length === 0) {
      return;
    }
    const SEQ = vscode.l10n.t("Sequential");
    const PAR = vscode.l10n.t("Parallel (fork…join)");
    const modePick =
      picked.length === 1
        ? SEQ
        : await vscode.window.showQuickPick([SEQ, PAR], {
            title: vscode.l10n.t("Virtual sequence: run mode"),
          });
    if (!modePick) {
      return;
    }
    const spec: ops.VseqSpec = {
      name,
      mode: modePick === PAR ? "parallel" : "sequential",
      steps: picked.map((a) => ({ agent: a, sequence: `${a}_seq` })),
    };
    if (await cfg.apply((t) => ops.addVirtualSequence(t, spec))) {
      this.log.appendLine(`[actions] addVirtualSequence ${name} (${picked.join(", ")})`);
    }
  }

  /**
   * Deletes a component of the verification environment (slice 2), with a MODAL
   * confirmation. Scoreboard/coverage/vseq are leaves (no one references them). For
   * an AGENT, the confirmation summarizes the cascade (its coverage, the scoreboards with
   * source/monitor == agent, the vseq steps) — the `removeAgent` mutation executes it.
   */
  async deleteComponent(
    kind: string,
    name: string,
    cfg: TbEditTarget = this.config
  ): Promise<void> {
    if (!cfg.configUri) {
      return this.warnNoConfig();
    }
    if (!name) {
      return;
    }
    let label: string;
    let detail: string | undefined;
    let mutate: (t: string) => string;
    switch (kind) {
      case "scoreboard":
        label = vscode.l10n.t('scoreboard "{0}"', name);
        mutate = (t) => ops.removeScoreboard(t, name);
        break;
      case "coverage":
        label = vscode.l10n.t('the coverage collector for "{0}"', name);
        mutate = (t) => ops.removeCoverage(t, name);
        break;
      case "vseq":
        label = vscode.l10n.t('virtual sequence "{0}"', name);
        mutate = (t) => ops.removeVirtualSequence(t, name);
        break;
      case "probe":
        label = vscode.l10n.t('probe "{0}"', name);
        mutate = (t) => ops.removeProbe(t, name);
        break;
      case "agent": {
        label = vscode.l10n.t('agent "{0}"', name);
        const cascade = this.agentCascade(name, cfg);
        if (cascade.length) {
          detail = vscode.l10n.t("This also removes: {0}.", cascade.join(", "));
        }
        mutate = (t) => ops.removeAgent(t, name);
        break;
      }
      default:
        return;
    }
    const DELETE = vscode.l10n.t("Delete");
    const pick = await vscode.window.showWarningMessage(
      vscode.l10n.t("Delete {0}?", label),
      { modal: true, detail },
      DELETE
    );
    if (pick !== DELETE) {
      return;
    }
    if (await cfg.apply(mutate)) {
      this.log.appendLine(`[actions] deleteComponent ${kind} ${name}`);
    }
  }

  /** The summary of what falls when an agent is deleted, for the modal confirmation. */
  private agentCascade(name: string, target: TbEditTarget): string[] {
    const cfg = target.current;
    const out: string[] = [];
    if ((cfg.analysis?.coverage ?? []).includes(name)) {
      out.push(vscode.l10n.t("its coverage collector"));
    }
    for (const s of cfg.analysis?.scoreboards ?? []) {
      if (s.source === name || s.monitor === name) {
        out.push(vscode.l10n.t('scoreboard "{0}"', s.name ?? "?"));
      }
    }
    for (const v of cfg.virtual_sequences ?? []) {
      const body = v.body ?? [];
      if (!body.some((st) => st.agent === name)) {
        continue;
      }
      // the sequence disappears only if ALL steps belong to the agent
      out.push(
        body.every((st) => st.agent === name)
          ? vscode.l10n.t('virtual sequence "{0}"', v.name ?? "?")
          : vscode.l10n.t('a step in "{0}"', v.name ?? "?")
      );
    }
    return out;
  }

  /**
   * Edits a field of a scoreboard (slice 2). The value comes from the inspector
   * (inline editing), empty => resets to default (match=in_order, field deleted
   * — see `setScoreboardField`). `max_latency` is converted to a number.
   */
  async editScoreboard(
    name: string,
    field: string,
    raw: string,
    cfg: TbEditTarget = this.config
  ): Promise<void> {
    if (!cfg.configUri || !name) {
      return;
    }
    const fields: ops.ScoreboardField[] = [
      "source",
      "monitor",
      "match",
      "match_key",
      "max_latency",
    ];
    if (!fields.includes(field as ops.ScoreboardField)) {
      return;
    }
    const f = field as ops.ScoreboardField;
    let value: string | number | undefined;
    if (raw === "") {
      value = undefined;
    } else if (f === "max_latency") {
      // latency = number of cycles: integer >= 0 (the input has min=0)
      const n = Number(raw);
      if (!Number.isInteger(n) || n < 0) {
        return;
      }
      value = n;
    } else {
      value = raw;
    }
    if (await cfg.apply((t) => ops.setScoreboardField(t, name, f, value))) {
      this.log.appendLine(`[actions] editScoreboard ${name}.${field} = ${raw || "(reset)"}`);
    }
  }

  /**
   * Whitebox probe (K2, slice 3) from a net selected in the schematic view:
   * the XMR path (relative to the DUT instance) and the width come from the MODEL through
   * `proposeProbe` (src/probe.ts, pure and tested); the name is confirmed by the
   * user. The refusals (subsystem bench, unpacked array, interface,
   * port already mapped on an agent) also come from there, with the reason displayed as such.
   */
  async createProbe(viewId: string | undefined, net: string): Promise<void> {
    if (!this.config.configUri) {
      return this.warnNoConfig();
    }
    const model = this.getModel();
    if (!model || !viewId || !net) {
      void vscode.window.showWarningMessage(
        vscode.l10n.t(
          "QuickUVM Architect: select a net in the schematic view first."
        )
      );
      return;
    }
    const check = proposeProbe(model, this.config.current, viewId, net);
    if (!check.ok) {
      void vscode.window.showWarningMessage(
        vscode.l10n.t("QuickUVM Architect: {0}", check.reason)
      );
      return;
    }
    const p = check.proposal;

    // The width: derived from the model when possible. When NOT (all endpoints go
    // through select/concat), we ask for it explicitly — left as default, QuickUVM makes
    // a 1-bit probe and silently TRUNCATES a wide signal.
    let width = p.width ?? undefined;
    if (width === undefined) {
      const raw = await vscode.window.showInputBox({
        title: vscode.l10n.t("Probe width (bits)"),
        value: "1",
        prompt: vscode.l10n.t(
          "the model cannot derive this net's width (its endpoints all go through select/concat) — left unset, QuickUVM would make it 1 bit and truncate"
        ),
        validateInput: (v) =>
          /^[1-9]\d*$/.test(v)
            ? undefined
            : vscode.l10n.t("a positive integer"),
      });
      if (!raw) {
        return;
      }
      width = Number(raw);
    }

    const taken = new Set(p.taken);
    const name = await vscode.window.showInputBox({
      title: vscode.l10n.t("Probe name"),
      value: Actions.uniqueName(p.name, taken),
      prompt: vscode.l10n.t("XMR path, relative to the DUT instance: {0}", p.path),
      validateInput: (v) =>
        !SV_IDENT_RE.test(v)
          ? vscode.l10n.t("invalid SystemVerilog identifier")
          : taken.has(v)
            ? vscode.l10n.t(
                "the name collides with another probe, an agent port/interface, the clock or the reset"
              )
            : undefined,
    });
    if (!name) {
      return;
    }

    // Functional coverage on the probe => `<dut>_probe_monitor` in the env; the
    // packaged anti-bug gate (K2 #1) lives in probe.ts (pure, tested)
    let coverage = false;
    if (probeCoverageAllowed(this.config.current)) {
      const NO = vscode.l10n.t("$(eye) Observe only");
      const YES = vscode.l10n.t("$(graph) Also collect functional coverage");
      const pick = await vscode.window.showQuickPick([NO, YES], {
        title: vscode.l10n.t("Probe: functional coverage"),
      });
      if (!pick) {
        return;
      }
      coverage = pick === YES;
    }

    const w = width;
    if (
      await this.config.apply((t) =>
        ops.addProbe(t, { name, path: p.path, width: w, coverage })
      )
    ) {
      this.log.appendLine(
        `[actions] createProbe ${name} -> ${p.path} (${w}b${coverage ? ", coverage" : ""})`
      );
      if (await this.isComposedChild()) {
        void vscode.window.showWarningMessage(
          vscode.l10n.t(
            "QuickUVM Architect: this config is composed as a subenv of another bench. QuickUVM 0.9.2 generates the probe files but never wires them into the subsystem testbench — the probe only works when this block is generated standalone."
          )
        );
      }
    }
  }

  /**
   * Is the active config referenced as `subenvs[].config` by another? Its probes would
   * be generated, but NOT wired into the subsystem's tb_top (no probe_if
   * instance, no XMR, no config_db, and not even in the filelist) — a real bug
   * of quick-uvm 0.9.2, which nevertheless exits with 0: SILENT failure, so we warn.
   */
  private async isComposedChild(): Promise<boolean> {
    const uri = this.config.configUri;
    if (!uri) {
      return false;
    }
    const found = await vscode.workspace.findFiles(
      "**/*.quickuvm.yaml",
      "**/node_modules/**"
    );
    const files = await Promise.all(
      found.map(async (u) => ({
        path: u.fsPath,
        text: Buffer.from(await vscode.workspace.fs.readFile(u)).toString("utf8"),
      }))
    );
    // the pure predicate (yamlops, tested) compares the paths normalized — includes()
    // on the raw fsPath misses the match on case differences on Windows
    return ops.isComposedChild(files, uri.fsPath);
  }

  /**
   * Derives the inter-block H1 connections from the nets of the subsystem's
   * schematic view and writes them into `connections` (slice 3, "derived composition").
   * Only for the current subsystem (config with `subenvs`, dut = the view's module).
   * The DESTINATION blocks must have a PASSIVE agent (`active: false`) — a
   * quick-uvm constraint; it is WARNED (the child configs are not edited silently,
   * as they are separate files owned by the user).
   */
  async wireConnections(viewId: string | undefined): Promise<void> {
    if (!this.config.configUri) {
      return this.warnNoConfig();
    }
    const model = this.getModel();
    const r = this.resolve(viewId);
    if (!model || !r) {
      return;
    }
    const cfg = this.config.current;
    if (cfg.dut?.name !== r.inst.module) {
      void vscode.window.showWarningMessage(
        vscode.l10n.t(
          "QuickUVM Architect: open the schematic of the subsystem DUT to wire its connections."
        )
      );
      return;
    }
    const subenvs = cfg.subenvs ?? [];
    if (!subenvs.length) {
      void vscode.window.showInformationMessage(
        vscode.l10n.t(
          "QuickUVM Architect: compose blocks as subenvs first (Create subenv)."
        )
      );
      return;
    }
    // child-rel -> subenv name, excluding the ambiguous names: the pure core
    // subenvMapping (compose.ts, tested) — invariant #3 of the composition
    const mapping = subenvMapping(
      model,
      r.inst.path,
      subenvs.map((s) => s.name)
    );
    const derived = deriveConnections(model, r.inst.path, mapping.subenvOf);
    if (mapping.ambiguous.length) {
      derived.warnings.push(
        `ambiguous subenv names, not wired: ${mapping.ambiguous.join(", ")}`
      );
    }
    if (derived.connections.length === 0) {
      const msg = derived.warnings.length
        ? derived.warnings.join("; ")
        : vscode.l10n.t("no inter-block connections found among the composed blocks.");
      void vscode.window.showInformationMessage(
        vscode.l10n.t("QuickUVM Architect: {0}", msg)
      );
      return;
    }
    // ATOMIC edit (a single undo) on MULTIPLE files: `connections` on the top +
    // the DESTINATION block's agent set passive in each child config (an input
    // port driven by a wire cannot also be driven by its own agent — quick-uvm
    // refuses otherwise). The child configs are separate files; we edit them
    // explicitly (not through ConfigService.apply, which touches only the active config).
    // The host only READS the files; the new texts come from planWireEdits
    // (compose.ts, pure, tested — including the folding on a shared file, #4).
    const topUri = this.config.configUri;
    const dir = vscode.Uri.joinPath(topUri, "..");
    const fullRange = (d: vscode.TextDocument): vscode.Range =>
      new vscode.Range(d.positionAt(0), d.positionAt(d.getText().length));

    const topDoc = await vscode.workspace.openTextDocument(topUri);
    const topOld = topDoc.getText();
    const children = new Map<string, { key: string; text: string }>();
    const childDocs = new Map<string, vscode.TextDocument>();
    for (const sink of derived.sinks) {
      const config = subenvs.find((s) => s.name === sink)?.config;
      if (!config || children.has(config)) {
        continue;
      }
      const childUri = vscode.Uri.joinPath(dir, config);
      try {
        const doc = await vscode.workspace.openTextDocument(childUri);
        children.set(config, { key: childUri.toString(), text: doc.getText() });
        childDocs.set(childUri.toString(), doc);
      } catch {
        // missing/unreadable file: the planner puts it under `manual`
      }
    }
    const plan = planWireEdits(topOld, subenvs, derived, children);
    const { passivated, manual } = plan;

    const edit = new vscode.WorkspaceEdit();
    if (plan.topText !== topOld) {
      edit.replace(topUri, fullRange(topDoc), plan.topText);
    }
    for (const [key, text] of plan.childTexts) {
      const doc = childDocs.get(key);
      if (doc) {
        edit.replace(doc.uri, fullRange(doc), text);
      }
    }

    if (!(await vscode.workspace.applyEdit(edit))) {
      void vscode.window.showErrorMessage(
        vscode.l10n.t("QuickUVM Architect: could not write the connections.")
      );
      return;
    }
    await this.config.refresh(); // synchronous: `current` immediately reflects the new YAML

    const parts = [
      vscode.l10n.t("{0} connection(s) wired", derived.connections.length),
    ];
    if (passivated.length) {
      parts.push(
        vscode.l10n.t("agents set passive: {0}", passivated.join(", "))
      );
    }
    if (manual.length) {
      // the child's skeleton has no agent yet (createSubenv does not create one) or
      // the config is missing: the user configures the agent and makes it passive
      parts.push(
        vscode.l10n.t(
          "configure and passivate the agent for: {0}",
          manual.join(", ")
        )
      );
    }
    for (const w of derived.warnings) {
      parts.push(w);
    }
    void vscode.window.showInformationMessage(
      `QuickUVM Architect: ${parts.join(" — ")}`
    );
    this.log.appendLine(
      `[actions] wireConnections: ${derived.connections.length} conn, ` +
        `${passivated.length} passivated, ${manual.length} manual` +
        (derived.warnings.length ? `, ${derived.warnings.length} warnings` : "")
    );
  }

  /**
   * "Compose into parent bench" (slice 3): from a BLOCK's view, composes the block
   * + its block SIBLINGS into the immediate PARENT bench. It reduces to `createSubenv`
   * targeting the parent (recursive ensureDut + skeleton + subenvs). A subsystem requires
   * ≥2 subenvs (quick-uvm), so all the parent's block children are composed;
   * the user confirms the list in createSubenv's QuickPick.
   */
  async composeIntoParent(viewId: string | undefined): Promise<void> {
    const model = this.getModel();
    if (!model || !viewId) {
      return;
    }
    const pc = parentComposition(model, viewId);
    if (!pc) {
      void vscode.window.showInformationMessage(
        vscode.l10n.t(
          "QuickUVM Architect: this is a top-level module — it has no parent bench."
        )
      );
      return;
    }
    if (pc.childRels.length < 2) {
      // quick-uvm constraint: a subsystem composes >=2 subenvs
      const parentModule =
        model.instances.find((i) => i.path === pc.parentPath)?.module ?? "?";
      void vscode.window.showWarningMessage(
        vscode.l10n.t(
          'QuickUVM Architect: the parent bench "{0}" has only {1} composable block(s) — a subsystem needs at least 2 subenvs.',
          parentModule,
          pc.childRels.length
        )
      );
      return;
    }
    // delegates to createSubenv, TARGETING the parent (ensureDut + skeleton + subenvs);
    // the user confirms the list of children in createSubenv's QuickPick
    await this.createSubenv(pc.parentPath, pc.childRels);
  }

  /**
   * Drill into the composed block (docs/05): opens the config file `configRel`
   * (the path from `subenvs[].config`, carried by the drill) with the DEFAULT editor of
   * `*.quickuvm.yaml` — i.e. the per-file TB diagram (slice 4). The path comes from
   * the block actually clicked, so duplicate names open distinct files.
   * The resolution mimics quick-uvm (pathlib): an ABSOLUTE path is taken as-is,
   * only the relative one is bound to the current config's directory. It works on
   * any TbEditTarget: the active config (panel) or the open document
   * (the per-file editor — H1 nesting across levels).
   */
  async openSubenvConfig(
    configRel: string,
    cfg: TbEditTarget = this.config
  ): Promise<void> {
    const uri = cfg.configUri;
    if (!uri || !configRel) {
      return;
    }
    // absolute path: do NOT append it as relative (Uri.joinPath would produce a
    // broken path — `/c:/proj/C:/abs/x.yaml`; quick-uvm accepts it as-is)
    const child = path.isAbsolute(configRel)
      ? vscode.Uri.file(configRel)
      : vscode.Uri.joinPath(uri, "..", configRel);
    try {
      // the default editor of *.quickuvm.yaml is QuvmConfigEditor (slice 4)
      await vscode.commands.executeCommand("vscode.open", child);
    } catch {
      void vscode.window.showWarningMessage(
        vscode.l10n.t('QuickUVM Architect: cannot open "{0}".', configRel)
      );
    }
  }

  private warnNoConfig(): void {
    void vscode.window.showWarningMessage(
      vscode.l10n.t('QuickUVM Architect: no configuration exists yet — use "Set as DUT".')
    );
  }

  private warnNoAgents(): void {
    void vscode.window.showWarningMessage(
      vscode.l10n.t("QuickUVM Architect: the active configuration has no agents yet.")
    );
  }

  /**
   * Active config with dut == the view's module — the subenvs' requirement (docs/03).
   * Without any config: the Set as DUT flow (checkDut). Active config on a DIFFERENT
   * dut: the recursive flow directly from the gesture — an explicit offer of a config
   * dedicated to the block, then Set as DUT on it; no dead button.
   */
  private async ensureDutForView(inst: Instance): Promise<boolean> {
    const dut = this.config.current.dut?.name;
    if (dut === inst.module) {
      return true;
    }
    if (!dut) {
      return this.checkDut(inst);
    }
    const create = vscode.l10n.t(
      "Create {0}.quickuvm.yaml and set its DUT",
      inst.module
    );
    const pick = await vscode.window.showInformationMessage(
      vscode.l10n.t(
        'Agents and subenvs for "{0}" belong to its own config, but the active config targets "{1}" (recursive flow, docs/03).',
        inst.module,
        dut
      ),
      create
    );
    if (pick !== create) {
      return false;
    }
    if (!(await this.config.createConfigFor(inst.module))) {
      return false;
    }
    // the new config is active and without a dut: the standard flow, without the
    // overwrite question (activeDut is now undefined)
    await this.setDut(inst.path);
    return this.config.current.dut?.name === inst.module;
  }

  // ------------------------------------------------------- ignorePorts

  async ignorePorts(pinIds: string[], ignore: boolean): Promise<void> {
    const names = pinIds.map((id) => id.replace(/^<port>\./, ""));
    if (names.length === 0) {
      return;
    }
    await this.config.apply((t) =>
      ignore ? ops.ignorePorts(t, names) : ops.unignorePorts(t, names)
    );
  }

  async fixPortWidth(agent: string, port: string, width: number): Promise<void> {
    await this.config.apply((t) => ops.setAgentPortWidth(t, agent, port, width));
  }

  // ------------------------------------------------------------ intern

  /** The agent actions require a DUT that is set and matches the current view. */
  private async checkDut(inst: Instance): Promise<boolean> {
    const dut = this.config.current.dut?.name;
    if (!dut) {
      const pick = await vscode.window.showInformationMessage(
        vscode.l10n.t("QuickUVM Architect: no DUT is configured yet."),
        vscode.l10n.t("Set this module as DUT")
      );
      if (pick) {
        await this.setDut(inst.path);
        return Boolean(this.config.current.dut?.name);
      }
      return false;
    }
    if (dut !== inst.module) {
      void vscode.window.showWarningMessage(
        vscode.l10n.t(
          "QuickUVM Architect: the configured DUT is \"{0}\", but the current view shows \"{1}\". Open the DUT view or change the DUT.",
          dut,
          inst.module
        )
      );
      return false;
    }
    return true;
  }

  private async askAgentName(suggestion: string): Promise<string | undefined> {
    const existing = new Set(
      (this.config.current.agents ?? []).map((a) => a.name)
    );
    return vscode.window.showInputBox({
      title: vscode.l10n.t("Agent name"),
      value: suggestion,
      prompt: vscode.l10n.t(
        "SystemVerilog identifier; prefixes the generated files"
      ),
      validateInput: (v) =>
        !SV_IDENT_RE.test(v)
          ? vscode.l10n.t("invalid SystemVerilog identifier")
          : existing.has(v)
            ? vscode.l10n.t("an agent with this name already exists")
            : undefined,
    });
  }

  /** The interface instance connected to the given port, through the parent's view. */
  private connectedIface(
    model: ProjectModel,
    inst: Instance,
    portName: string,
    ifaceModule: string
  ): Instance | undefined {
    // the parent = the longest instance path that is a proper prefix of the current path
    let parent: Instance | undefined;
    for (const i of model.instances) {
      if (
        inst.path.startsWith(i.path + ".") &&
        (!parent || i.path.length > parent.path.length)
      ) {
        parent = i;
      }
    }
    if (parent) {
      const rel = inst.path.slice(parent.path.length + 1);
      const view = model.views[parent.path];
      const pin = view?.pins.find((p) => p.pin === `${rel}.${portName}`);
      if (pin?.conn && pin.conn.kind === "iface") {
        const base = pin.conn.ref.split(".")[0];
        const found = model.instances.find(
          (i) => i.path === `${parent.path}.${base}`
        );
        if (found?.iface) {
          return found;
        }
      }
    }
    // fallback: the sole instance of that interface type in the design
    const candidates = model.instances.filter(
      (i) => i.module === ifaceModule && i.iface
    );
    return candidates.length === 1 ? candidates[0] : undefined;
  }
}

/** `g_ch[0..2].u_ch` -> the member paths; an id without a fold stays as-is. */
function expandFold(rel: string): string[] {
  const m = /\[(\d+)\.\.(\d+)\]/.exec(rel);
  if (!m) {
    return [rel];
  }
  const out: string[] = [];
  for (let i = Number(m[1]); i <= Number(m[2]); i++) {
    out.push(rel.replace(m[0], `[${i}]`));
  }
  return out;
}

/** the heuristic dut of a child block (the skeleton from createSubenv, docs/03) */
function heuristicDut(module: string, def: ModuleDef | undefined): ops.DutSpec {
  const oneBitIns = (def?.ports ?? []).filter(
    (p) => p.dir === "in" && p.width === 1
  );
  const clock = oneBitIns.find((p) => CLOCK_RE.test(p.name))?.name ?? null;
  const reset = oneBitIns.find((p) => RESET_RE.test(p.name))?.name ?? null;
  return {
    module,
    clock,
    reset,
    resetActiveLow: reset ? ACTIVE_LOW_RE.test(reset) : true,
    externalReset: false,
    combinational: !clock,
  };
}

/** Agent name suggestion from the common prefix of the selected pins. */
export function suggestName(pinNames: string[]): string {
  const names = pinNames.map((n) => n.replace(/^<port>\./, ""));
  if (names.length === 1) {
    return names[0];
  }
  const first = names[0] ?? "agent";
  let prefix = first;
  for (const n of names) {
    while (prefix && !n.startsWith(prefix)) {
      prefix = prefix.slice(0, -1);
    }
  }
  prefix = prefix.replace(/_+$/, "");
  return SV_IDENT_RE.test(prefix) ? prefix : "agent1";
}
