// Actiunile de configurare QuickUVM (docs/03): setDut cu euristici
// confirmate explicit, agent din selectie de pini (cu inversarea
// perspectivei!), agent din interfata (desfacerea modportului), ignorare de
// porturi. Toate produc editari YAML prin ConfigService.apply (WorkspaceEdit).

import * as path from "path";
import * as vscode from "vscode";
import {
  deriveConnections,
  parentComposition,
  planWireEdits,
  subenvMapping,
  subenvName,
} from "./compose";
import { ConfigService, TbEditTarget } from "./config";
// euristicile pe nume (inclusiv capcana _ni/_bi) stau in heuristics (pur, testat)
import { ACTIVE_LOW_RE, CLOCK_RE, RESET_RE, SV_IDENT_RE } from "./heuristics";
import { Instance, ModuleDef, Port, ProjectModel } from "./model";
import { probeCoverageAllowed, proposeProbe } from "./probe";
import * as ops from "./yamlops";

export class Actions {
  constructor(
    private readonly getModel: () => ProjectModel | undefined,
    private readonly config: ConfigService,
    private readonly log: vscode.OutputChannel
  ) {}

  private resolve(
    viewId: string | undefined
  ): { inst: Instance; def: ModuleDef } | undefined {
    const model = this.getModel();
    const inst = model?.instances.find((i) => i.path === viewId);
    const def = inst ? model?.modules[inst.module] : undefined;
    if (!inst || !def) {
      void vscode.window.showWarningMessage(
        vscode.l10n.t(
          "QuickUVM Architect: open the symbol view of an instance first."
        )
      );
      return undefined;
    }
    return { inst, def };
  }

  // ------------------------------------------------------------- setDut

  /** Desemnarea DUT-ului cu propuneri euristice, niciodata aplicate tacit. */
  async setDut(viewId: string | undefined): Promise<void> {
    const r = this.resolve(viewId);
    if (!r) {
      return;
    }
    const { inst, def } = r;
    const oneBitIns = def.ports.filter((p) => p.dir === "in" && p.width === 1);
    let clock = oneBitIns.find((p) => CLOCK_RE.test(p.name))?.name ?? null;
    const reset = oneBitIns.find((p) => RESET_RE.test(p.name))?.name ?? null;

    type Item = vscode.QuickPickItem & { id: string };
    const items: Item[] = [];
    if (clock) {
      items.push({
        id: "clock",
        label: vscode.l10n.t("$(watch) Clock: {0}", clock),
        detail: vscode.l10n.t("heuristic — uncheck if this is not the clock"),
        picked: true,
      });
    } else {
      items.push({
        id: "comb",
        label: vscode.l10n.t(
          "$(circuit-board) Combinational DUT (no clock of its own)"
        ),
        detail: vscode.l10n.t(
          "no clock candidate found; the testbench cadence remains"
        ),
        picked: true,
      });
    }
    if (reset) {
      const low = ACTIVE_LOW_RE.test(reset);
      items.push({
        id: "reset",
        label: vscode.l10n.t(
          "$(refresh) Reset: {0} (active on {1})",
          reset,
          low ? "0" : "1"
        ),
        picked: true,
      });
      items.push({
        id: "external",
        label: vscode.l10n.t(
          "$(plug) External reset (generated by the testbench, not by the agent)"
        ),
        picked: false,
      });
    }
    const picked = await vscode.window.showQuickPick(items, {
      canPickMany: true,
      title: vscode.l10n.t("Set as DUT: {0}", inst.module),
      placeHolder: vscode.l10n.t("Confirm the heuristic proposals (docs/03)"),
    });
    if (!picked) {
      return;
    }
    const has = (id: string) => picked.some((i) => i.id === id);

    if (clock && !has("clock")) {
      clock = null;
    }
    let combinational = !clock && (has("comb") || !items.some((i) => i.id === "comb"));
    if (!clock && !has("comb") && items.some((i) => i.id === "comb")) {
      // utilizatorul refuza si combinational: alege manual ceasul
      const pick = await vscode.window.showQuickPick(
        oneBitIns.map((p) => p.name),
        { title: vscode.l10n.t("Choose the clock port") }
      );
      if (!pick) {
        return;
      }
      clock = pick;
      combinational = false;
    }

    const spec: ops.DutSpec = {
      module: inst.module,
      clock,
      reset: has("reset") && reset ? reset : null,
      resetActiveLow: reset ? ACTIVE_LOW_RE.test(reset) : true,
      externalReset: has("external"),
      combinational,
    };
    // config activ pe ALT dut: alegere explicita — suprascrie dut-ul
    // config-ului activ (semantica fazei 2) sau creeaza config-ul dedicat
    // blocului (fluxul recursiv al compunerii, docs/03); nimic tacit
    const activeDut = this.config.current.dut?.name;
    let uri: vscode.Uri | undefined;
    if (activeDut && activeDut !== inst.module && this.config.configUri) {
      const overwrite = vscode.l10n.t(
        "Change the DUT of the active config ({0} → {1})",
        activeDut,
        inst.module
      );
      const fresh = vscode.l10n.t(
        "Create {0}.quickuvm.yaml for this block (subenv child config)",
        inst.module
      );
      const pick = await vscode.window.showQuickPick([fresh, overwrite], {
        title: vscode.l10n.t("Set as DUT: {0}", inst.module),
        placeHolder: vscode.l10n.t(
          'The active config targets "{0}" — choose what to do',
          activeDut
        ),
      });
      if (!pick) {
        return;
      }
      uri =
        pick === fresh
          ? await this.config.createConfigFor(inst.module)
          : await this.config.ensureConfig(inst.module);
    } else {
      uri = await this.config.ensureConfig(inst.module);
    }
    if (!uri) {
      return;
    }
    if (await this.config.apply((t) => ops.setDut(t, spec))) {
      this.log.appendLine(`[actions] setDut ${inst.module} -> ${uri.fsPath}`);
    }
  }

  // ------------------------------------------------- agent din selectie

  /**
   * Agent din pinii selectati. Directiile YAML sunt din perspectiva DUT-ului
   * (docs/03): intrarile DUT devin `inputs` (agentul le conduce), iesirile
   * `outputs` cu randomize: false.
   */
  async createAgentFromPins(
    viewId: string | undefined,
    pinIds: string[]
  ): Promise<void> {
    const r = this.resolve(viewId);
    if (!r) {
      return;
    }
    const { inst, def } = r;
    if (!(await this.ensureDutForView(inst))) {
      return;
    }
    const names = pinIds
      .map((id) => id.replace(/^<port>\./, ""))
      .filter((n, i, all) => all.indexOf(n) === i);
    const ports = names
      .map((n) => def.ports.find((p) => p.name === n))
      .filter((p): p is Port => Boolean(p));
    if (ports.length === 0) {
      void vscode.window.showWarningMessage(
        vscode.l10n.t(
          "QuickUVM Architect: select the DUT pins for the agent first."
        )
      );
      return;
    }

    const roles = this.config.lastOverlay?.roles ?? {};
    const inputs: ops.AgentPortSpec[] = [];
    const outputs: ops.AgentPortSpec[] = [];
    const skipped: string[] = [];

    for (const p of ports) {
      if (roles[p.name] === "clock" || roles[p.name] === "reset") {
        skipped.push(vscode.l10n.t("{0} (role {1})", p.name, roles[p.name]));
        continue;
      }
      if (p.dir === "inout" || p.dir === "ref") {
        skipped.push(
          vscode.l10n.t("{0} (inout not supported by the QuickUVM schema)", p.name)
        );
        continue;
      }
      if (p.width === null) {
        skipped.push(vscode.l10n.t("{0} (no fixed size)", p.name));
        continue;
      }
      let width = p.width;
      if (p.unpacked_dims) {
        // tablou unpacked: decizie explicita per port (docs/03)
        const flat = vscode.l10n.t("Flatten (width={0})", p.width);
        const choice = await vscode.window.showQuickPick(
          [flat, vscode.l10n.t("Exclude the port")],
          {
            title: vscode.l10n.t(
              "\"{0}\" is an unpacked array {1} × {2} bits — QuickUVM has no such notion",
              p.name,
              JSON.stringify(p.unpacked_dims),
              String(p.elem_width)
            ),
          }
        );
        if (!choice) {
          return;
        }
        if (choice !== flat) {
          skipped.push(vscode.l10n.t("{0} (unpacked array excluded)", p.name));
          continue;
        }
        width = p.width;
      }
      (p.dir === "in" ? inputs : outputs).push({ name: p.name, width });
    }

    if (inputs.length + outputs.length === 0) {
      void vscode.window.showWarningMessage(
        vscode.l10n.t(
          "QuickUVM Architect: no usable pin in the selection ({0}).",
          skipped.join("; ")
        )
      );
      return;
    }

    const name = await this.askAgentName(suggestName(names));
    if (!name) {
      return;
    }
    const style = vscode.workspace
      .getConfiguration("quickuvm")
      .get<"manual" | "field_macros">("seqItemStyle", "manual");

    if (
      await this.config.apply((t) =>
        ops.createAgent(t, { name, inputs, outputs, seqItemStyle: style })
      )
    ) {
      const note = skipped.length
        ? vscode.l10n.t(" (excluded: {0})", skipped.join("; "))
        : "";
      void vscode.window.showInformationMessage(
        vscode.l10n.t(
          "QuickUVM Architect: agent \"{0}\" with {1} inputs / {2} outputs{3}.",
          name,
          inputs.length,
          outputs.length,
          note
        )
      );
    }
  }

  // ------------------------------------------------ agent din interfata

  /** Agent din portul de interfata: desface modportul DUT-ului (docs/03). */
  async createAgentFromIface(
    viewId: string | undefined,
    portName: string
  ): Promise<void> {
    const model = this.getModel();
    const r = this.resolve(viewId);
    if (!r || !model) {
      return;
    }
    const { inst, def } = r;
    if (!(await this.ensureDutForView(inst))) {
      return;
    }
    const ifp = def.iface_ports.find((p) => p.name === portName);
    if (!ifp) {
      return;
    }

    // instanta de interfata conectata: prin vederea parintelui, altfel dupa tip
    const ifaceInst = this.connectedIface(model, inst, portName, ifp.interface);
    if (!ifaceInst?.iface) {
      void vscode.window.showWarningMessage(
        vscode.l10n.t(
          "QuickUVM Architect: cannot find an instance of interface \"{0}\" with elaborated signals.",
          ifp.interface
        )
      );
      return;
    }
    const modportName = ifp.modport ?? "";
    const modport = ifaceInst.iface.modports[modportName];
    if (!modport) {
      void vscode.window.showWarningMessage(
        vscode.l10n.t(
          "QuickUVM Architect: interface \"{0}\" has no modport \"{1}\" in the model.",
          ifp.interface,
          modportName
        )
      );
      return;
    }

    const widths = new Map(
      ifaceInst.iface.signals.map((s) => [s.name, s.width])
    );
    const inputs: ops.AgentPortSpec[] = [];
    const outputs: ops.AgentPortSpec[] = [];
    const skipped: string[] = [];
    for (const [signal, dir] of Object.entries(modport)) {
      const width = widths.get(signal) ?? null;
      if (CLOCK_RE.test(signal) && width === 1) {
        skipped.push(vscode.l10n.t("{0} (interface clock -> dut.clock)", signal));
        continue;
      }
      if (width === null) {
        skipped.push(vscode.l10n.t("{0} (no fixed size)", signal));
        continue;
      }
      // aceeasi inversare de perspectiva: semnal `in` in modportul DUT-ului
      // => DUT-ul il primeste => agentul il conduce => inputs
      if (dir === "in") {
        inputs.push({ name: signal, width });
      } else if (dir === "out") {
        outputs.push({ name: signal, width });
      } else {
        skipped.push(vscode.l10n.t("{0} ({1} not supported)", signal, dir));
      }
    }
    if (inputs.length + outputs.length === 0) {
      void vscode.window.showWarningMessage(
        vscode.l10n.t(
          "QuickUVM Architect: modport \"{0}\" has no usable signals ({1}).",
          modportName,
          skipped.join("; ")
        )
      );
      return;
    }

    const name = await this.askAgentName(portName);
    if (!name) {
      return;
    }
    const style = vscode.workspace
      .getConfiguration("quickuvm")
      .get<"manual" | "field_macros">("seqItemStyle", "manual");
    if (
      await this.config.apply((t) =>
        ops.createAgent(t, { name, inputs, outputs, seqItemStyle: style })
      )
    ) {
      const note = skipped.length
        ? vscode.l10n.t(" (excluded: {0})", skipped.join("; "))
        : "";
      void vscode.window.showInformationMessage(
        vscode.l10n.t(
          "QuickUVM Architect: agent \"{0}\" from {1}.{2}{3}. The original SV interface remains the source of the specification; QuickUVM generates its own {0}_if.sv (known limitation, docs/03).",
          name,
          ifp.interface,
          modportName,
          note
        )
      );
    }
  }

  // ------------------------------------------------------ createSubenv

  /**
   * Subenv-uri H1 din blocurile selectate in vederea-schema (docs/03): un
   * subenv per instanta (pliajele se desfac in membri), config-ul copilului
   * `<modul>.quickuvm.yaml` linga config-ul top, creat la nevoie cu schelet +
   * dut euristic; params doar cu valori intregi (schema cere dict[str, int]).
   * Constringerile H1 din QuickUVM (copii doar combinationali; params cer
   * `parameters:` declarati in agentul blocului) se semnaleaza in confirmare.
   */
  async createSubenv(
    viewId: string | undefined,
    nodeIds: string[]
  ): Promise<void> {
    const model = this.getModel();
    const r = this.resolve(viewId);
    if (!r || !model) {
      return;
    }
    const { inst } = r;
    if (!(await this.ensureDutForView(inst))) {
      return;
    }
    const topUri = this.config.configUri;
    if (!topUri) {
      return;
    }

    // selectia -> instante-copil: pliajele se desfac, interfetele se sar
    const rels = [...new Set(nodeIds.flatMap(expandFold))];
    const targets: { rel: string; child: Instance }[] = [];
    for (const rel of rels) {
      const child = model.instances.find(
        (i) => i.path === `${inst.path}.${rel}`
      );
      if (child && !child.iface) {
        targets.push({ rel, child });
      }
    }
    if (targets.length === 0) {
      void vscode.window.showWarningMessage(
        vscode.l10n.t(
          "QuickUVM Architect: select one or more child blocks in the schematic view first."
        )
      );
      return;
    }

    // propuneri: nume unice; subenv-urile deja prezente in YAML se sar
    const existing = new Set(
      (this.config.current.subenvs ?? [])
        .map((s) => s.name)
        .filter((n): n is string => Boolean(n))
    );
    const used = new Set(existing);
    const already: string[] = [];
    interface Proposal {
      name: string;
      rel: string;
      module: string;
      configFile: string;
      params: Record<string, number>;
      skippedParams: string[];
    }
    const proposals: Proposal[] = [];
    for (const { rel, child } of targets) {
      const base = subenvName(rel);
      if (existing.has(base)) {
        already.push(rel);
        continue;
      }
      let name = base;
      for (let n = 2; used.has(name); n++) {
        name = `${base}_${n}`;
      }
      used.add(name);
      const params: Record<string, number> = {};
      const skippedParams: string[] = [];
      for (const [k, v] of Object.entries(child.params)) {
        if (/^-?\d+$/.test(v.trim())) {
          params[k] = Number(v.trim());
        } else {
          skippedParams.push(`${k}=${v}`);
        }
      }
      proposals.push({
        name,
        rel,
        module: child.module,
        configFile: `${child.module}.quickuvm.yaml`,
        params,
        skippedParams,
      });
    }
    if (proposals.length === 0) {
      void vscode.window.showInformationMessage(
        vscode.l10n.t(
          "QuickUVM Architect: the selected blocks are already subenvs ({0}).",
          already.join(", ")
        )
      );
      return;
    }

    // config-urile copil lipsa: schelet + dut euristic, rezumat in confirmare
    const dir = vscode.Uri.joinPath(topUri, "..");
    const newConfigs = new Map<string, { uri: vscode.Uri; spec: ops.DutSpec }>();
    for (const p of proposals) {
      if (newConfigs.has(p.module)) {
        continue;
      }
      const uri = vscode.Uri.joinPath(dir, p.configFile);
      try {
        await vscode.workspace.fs.stat(uri);
      } catch {
        newConfigs.set(p.module, {
          uri,
          spec: heuristicDut(p.module, this.getModel()?.modules[p.module]),
        });
      }
    }

    type Item = vscode.QuickPickItem & { proposal: Proposal };
    const items: Item[] = proposals.map((p) => {
      const fresh = newConfigs.get(p.module);
      const notes: string[] = [];
      if (Object.keys(p.params).length) {
        notes.push(
          `params: {${Object.entries(p.params)
            .map(([k, v]) => `${k}: ${v}`)
            .join(", ")}}`
        );
      }
      if (p.skippedParams.length) {
        notes.push(
          vscode.l10n.t("non-integer params omitted: {0}",
            p.skippedParams.join(", "))
        );
      }
      if (fresh) {
        // copiii cu ceas sunt acceptati de compunerea H1 din slice-ul M1
        // clocked-subenv (single-clock, cel mult un reset) — scheletul
        // euristic satisface mereu conditia
        notes.push(
          fresh.spec.combinational
            ? vscode.l10n.t("new config (combinational DUT)")
            : vscode.l10n.t(
                "new config (clock: {0}, reset: {1})",
                fresh.spec.clock ?? "?",
                fresh.spec.reset ?? "—"
              )
        );
      }
      return {
        proposal: p,
        label: p.name,
        description: `${p.module} → ${p.configFile}`,
        detail: notes.join(" • ") || undefined,
        picked: true,
      };
    });
    const picked = await vscode.window.showQuickPick(items, {
      canPickMany: true,
      title: vscode.l10n.t("Create subenvs in {0}", inst.module),
      placeHolder: vscode.l10n.t(
        "Confirm the subenvs to add (docs/03); params require the block agent to declare `parameters:`"
      ),
    });
    if (!picked || picked.length === 0) {
      return;
    }

    // 1. config-urile copil lipsa, doar pentru modulele confirmate
    const chosenModules = new Set(picked.map((i) => i.proposal.module));
    const creations = [...newConfigs.entries()].filter(([m]) =>
      chosenModules.has(m)
    );
    if (creations.length) {
      const edit = new vscode.WorkspaceEdit();
      for (const [module, c] of creations) {
        edit.createFile(c.uri, {
          ignoreIfExists: true,
          contents: Buffer.from(
            ops.setDut(ops.newConfigText(module), c.spec),
            "utf8"
          ),
        });
      }
      await vscode.workspace.applyEdit(edit);
      for (const [, c] of creations) {
        this.log.appendLine(`[actions] createSubenv: created ${c.uri.fsPath}`);
      }
    }

    // gard hibrid: quick-uvm INTERZICE `subenvs` + agenti proprii — daca
    // config-ul tinta are deja agenti, compunerea l-ar face invalid (generate ar
    // esua). Confirmam explicit; utilizatorul poate continua (si scoate agentii)
    if ((this.config.current.agents?.length ?? 0) > 0) {
      const PROCEED = vscode.l10n.t("Compose anyway");
      const pick = await vscode.window.showWarningMessage(
        vscode.l10n.t(
          'The config for "{0}" defines its own agents. QuickUVM rejects a bench that has both agents and subenvs — you will need to remove the agents. Compose anyway?',
          inst.module
        ),
        { modal: true },
        PROCEED
      );
      if (pick !== PROCEED) {
        return;
      }
    }

    // 2. intrarile subenvs in config-ul top (un singur WorkspaceEdit)
    const specs: ops.SubenvSpec[] = picked.map((i) => ({
      name: i.proposal.name,
      config: i.proposal.configFile,
      params: i.proposal.params,
    }));
    if (await this.config.apply((t) => ops.createSubenvs(t, specs))) {
      const notes: string[] = [];
      if (creations.length) {
        notes.push(
          vscode.l10n.t(
            "{0} new block config(s) — configure their agents next (recursive flow, docs/03)",
            creations.length
          )
        );
      }
      if (already.length) {
        notes.push(
          vscode.l10n.t("already subenvs: {0}", already.join(", "))
        );
      }
      void vscode.window.showInformationMessage(
        vscode.l10n.t(
          "QuickUVM Architect: {0} subenv(s) added{1}.",
          specs.length,
          notes.length ? ` (${notes.join("; ")})` : ""
        )
      );
    }
  }

  // ------------------------------------ vederea de verificare (3b, felia 2)

  /** numele agentilor din config-ul activ */
  private agentNames(cfg: TbEditTarget, activeOnly = false): string[] {
    return (cfg.current.agents ?? [])
      .filter((a) => !activeOnly || a.active !== false)
      .map((a) => a.name)
      .filter((n): n is string => Boolean(n));
  }

  /** un nume unic pentru o intrare noua (`base`, apoi `base2`, `base3`…) */
  private static uniqueName(base: string, taken: Set<string>): string {
    if (!taken.has(base)) {
      return base;
    }
    for (let n = 2; ; n++) {
      const name = `${base}${n}`;
      if (!taken.has(name)) {
        return name;
      }
    }
  }

  /** Colector de coverage pentru un agent (`analysis.coverage`, docs/03).
   *  `cfg` = config-ul activ (panel) SAU documentul deschis (CustomTextEditor). */
  async addCoverage(preselect?: string, cfg: TbEditTarget = this.config): Promise<void> {
    if (!cfg.configUri) {
      return this.warnNoConfig();
    }
    const agents = this.agentNames(cfg);
    if (!agents.length) {
      return this.warnNoAgents();
    }
    const covered = new Set(cfg.current.analysis?.coverage ?? []);
    const choices = agents.filter((a) => !covered.has(a));
    if (!choices.length) {
      void vscode.window.showInformationMessage(
        vscode.l10n.t("QuickUVM Architect: every agent already has a coverage collector.")
      );
      return;
    }
    let agent = preselect && choices.includes(preselect) ? preselect : undefined;
    if (!agent) {
      agent = await vscode.window.showQuickPick(choices, {
        title: vscode.l10n.t("Coverage collector for agent"),
      });
      if (!agent) {
        return;
      }
    }
    const a = agent;
    if (await cfg.apply((t) => ops.addCoverage(t, a))) {
      this.log.appendLine(`[actions] addCoverage ${a}`);
    }
  }

  /** Scoreboard din fluxurile agentilor (`analysis.scoreboards`, docs/03). */
  async addScoreboard(preselSource?: string, cfg: TbEditTarget = this.config): Promise<void> {
    if (!cfg.configUri) {
      return this.warnNoConfig();
    }
    const agents = this.agentNames(cfg);
    if (!agents.length) {
      return this.warnNoAgents();
    }
    let source =
      preselSource && agents.includes(preselSource) ? preselSource : undefined;
    if (!source) {
      source = await vscode.window.showQuickPick(agents, {
        title: vscode.l10n.t("Scoreboard: stimulus/source agent"),
        placeHolder: vscode.l10n.t("the stream fed into the predictor"),
      });
      if (!source) {
        return;
      }
    }
    const src = source;
    const NONE = vscode.l10n.t("$(circle-slash) None (single-stream)");
    const monPick = await vscode.window.showQuickPick(
      [NONE, ...agents.filter((a) => a !== src)],
      {
        title: vscode.l10n.t("Scoreboard: response/monitor agent (A2 two-stream)"),
        placeHolder: vscode.l10n.t("the observed stream compared against the prediction"),
      }
    );
    if (monPick === undefined) {
      return;
    }
    const monitor = monPick === NONE ? undefined : monPick;

    let match: "in_order" | "out_of_order" = "in_order";
    let matchKey: string | undefined;
    if (monitor) {
      const IN = vscode.l10n.t("In order (FIFO pair)");
      const OOO = vscode.l10n.t("Out of order (keyed pool — a reordering DUT)");
      const mPick = await vscode.window.showQuickPick([IN, OOO], {
        title: vscode.l10n.t("Scoreboard: comparison strategy"),
      });
      if (!mPick) {
        return;
      }
      if (mPick === OOO) {
        match = "out_of_order";
        matchKey = await vscode.window.showInputBox({
          title: vscode.l10n.t("Match key (monitor transaction field)"),
          prompt: vscode.l10n.t("the field each response is keyed on (required for out-of-order)"),
          validateInput: (v) =>
            SV_IDENT_RE.test(v)
              ? undefined
              : vscode.l10n.t("invalid SystemVerilog identifier"),
        });
        if (!matchKey) {
          return;
        }
      }
    }

    const taken = new Set(
      (cfg.current.analysis?.scoreboards ?? [])
        .map((s) => s.name)
        .filter((n): n is string => Boolean(n))
    );
    const name = await vscode.window.showInputBox({
      title: vscode.l10n.t("Scoreboard name"),
      value: Actions.uniqueName("sbd", taken),
      validateInput: (v) =>
        !SV_IDENT_RE.test(v)
          ? vscode.l10n.t("invalid SystemVerilog identifier")
          : taken.has(v)
            ? vscode.l10n.t("a scoreboard with this name already exists")
            : undefined,
    });
    if (!name) {
      return;
    }
    if (
      await cfg.apply((t) =>
        ops.addScoreboard(t, { name, source: src, monitor, match, matchKey })
      )
    ) {
      this.log.appendLine(
        `[actions] addScoreboard ${name} (${src}${monitor ? ` vs ${monitor}` : ""})`
      );
    }
  }

  /** Secventa virtuala coordonand sequencerii agentilor activi (C2, docs/03). */
  async addVirtualSequence(cfg: TbEditTarget = this.config): Promise<void> {
    if (!cfg.configUri) {
      return this.warnNoConfig();
    }
    const active = this.agentNames(cfg, true);
    if (!active.length) {
      void vscode.window.showWarningMessage(
        vscode.l10n.t("QuickUVM Architect: a virtual sequence needs at least one active agent.")
      );
      return;
    }
    const taken = new Set(
      (cfg.current.virtual_sequences ?? [])
        .map((v) => v.name)
        .filter((n): n is string => Boolean(n))
    );
    const name = await vscode.window.showInputBox({
      title: vscode.l10n.t("Virtual sequence name"),
      value: Actions.uniqueName("vseq", taken),
      validateInput: (v) =>
        !SV_IDENT_RE.test(v)
          ? vscode.l10n.t("invalid SystemVerilog identifier")
          : taken.has(v)
            ? vscode.l10n.t("a virtual sequence with this name already exists")
            : undefined,
    });
    if (!name) {
      return;
    }
    const picked =
      active.length === 1
        ? active
        : await vscode.window.showQuickPick(
            active.map((a) => ({ label: a, picked: true })),
            {
              canPickMany: true,
              title: vscode.l10n.t("Virtual sequence: agents to coordinate"),
            }
          ).then((sel) => sel?.map((i) => i.label));
    if (!picked || picked.length === 0) {
      return;
    }
    const SEQ = vscode.l10n.t("Sequential");
    const PAR = vscode.l10n.t("Parallel (fork…join)");
    const modePick =
      picked.length === 1
        ? SEQ
        : await vscode.window.showQuickPick([SEQ, PAR], {
            title: vscode.l10n.t("Virtual sequence: run mode"),
          });
    if (!modePick) {
      return;
    }
    const spec: ops.VseqSpec = {
      name,
      mode: modePick === PAR ? "parallel" : "sequential",
      steps: picked.map((a) => ({ agent: a, sequence: `${a}_seq` })),
    };
    if (await cfg.apply((t) => ops.addVirtualSequence(t, spec))) {
      this.log.appendLine(`[actions] addVirtualSequence ${name} (${picked.join(", ")})`);
    }
  }

  /**
   * Sterge o componenta a mediului de verificare (felia 2), cu confirmare
   * MODALA. Scoreboard/coverage/vseq sunt frunze (nimeni nu le refera). Pentru
   * un AGENT, confirmarea rezuma cascada (coverage-ul lui, scoreboard-urile cu
   * source/monitor == agent, pasii de vseq) — mutatia `removeAgent` o executa.
   */
  async deleteComponent(
    kind: string,
    name: string,
    cfg: TbEditTarget = this.config
  ): Promise<void> {
    if (!cfg.configUri) {
      return this.warnNoConfig();
    }
    if (!name) {
      return;
    }
    let label: string;
    let detail: string | undefined;
    let mutate: (t: string) => string;
    switch (kind) {
      case "scoreboard":
        label = vscode.l10n.t('scoreboard "{0}"', name);
        mutate = (t) => ops.removeScoreboard(t, name);
        break;
      case "coverage":
        label = vscode.l10n.t('the coverage collector for "{0}"', name);
        mutate = (t) => ops.removeCoverage(t, name);
        break;
      case "vseq":
        label = vscode.l10n.t('virtual sequence "{0}"', name);
        mutate = (t) => ops.removeVirtualSequence(t, name);
        break;
      case "probe":
        label = vscode.l10n.t('probe "{0}"', name);
        mutate = (t) => ops.removeProbe(t, name);
        break;
      case "agent": {
        label = vscode.l10n.t('agent "{0}"', name);
        const cascade = this.agentCascade(name, cfg);
        if (cascade.length) {
          detail = vscode.l10n.t("This also removes: {0}.", cascade.join(", "));
        }
        mutate = (t) => ops.removeAgent(t, name);
        break;
      }
      default:
        return;
    }
    const DELETE = vscode.l10n.t("Delete");
    const pick = await vscode.window.showWarningMessage(
      vscode.l10n.t("Delete {0}?", label),
      { modal: true, detail },
      DELETE
    );
    if (pick !== DELETE) {
      return;
    }
    if (await cfg.apply(mutate)) {
      this.log.appendLine(`[actions] deleteComponent ${kind} ${name}`);
    }
  }

  /** Rezumatul a ce cade la stergerea unui agent, pentru confirmarea modala. */
  private agentCascade(name: string, target: TbEditTarget): string[] {
    const cfg = target.current;
    const out: string[] = [];
    if ((cfg.analysis?.coverage ?? []).includes(name)) {
      out.push(vscode.l10n.t("its coverage collector"));
    }
    for (const s of cfg.analysis?.scoreboards ?? []) {
      if (s.source === name || s.monitor === name) {
        out.push(vscode.l10n.t('scoreboard "{0}"', s.name ?? "?"));
      }
    }
    for (const v of cfg.virtual_sequences ?? []) {
      const body = v.body ?? [];
      if (!body.some((st) => st.agent === name)) {
        continue;
      }
      // secventa dispare doar daca TOTI pasii sunt ai agentului
      out.push(
        body.every((st) => st.agent === name)
          ? vscode.l10n.t('virtual sequence "{0}"', v.name ?? "?")
          : vscode.l10n.t('a step in "{0}"', v.name ?? "?")
      );
    }
    return out;
  }

  /**
   * Editeaza un camp al unui scoreboard (felia 2). Valoarea vine din inspector
   * (editare inline), gol => reseteaza la implicit (match=in_order, camp sters
   * — vezi `setScoreboardField`). `max_latency` se converteste la numar.
   */
  async editScoreboard(
    name: string,
    field: string,
    raw: string,
    cfg: TbEditTarget = this.config
  ): Promise<void> {
    if (!cfg.configUri || !name) {
      return;
    }
    const fields: ops.ScoreboardField[] = [
      "source",
      "monitor",
      "match",
      "match_key",
      "max_latency",
    ];
    if (!fields.includes(field as ops.ScoreboardField)) {
      return;
    }
    const f = field as ops.ScoreboardField;
    let value: string | number | undefined;
    if (raw === "") {
      value = undefined;
    } else if (f === "max_latency") {
      // latenta = numar de cicluri: intreg >= 0 (input-ul are min=0)
      const n = Number(raw);
      if (!Number.isInteger(n) || n < 0) {
        return;
      }
      value = n;
    } else {
      value = raw;
    }
    if (await cfg.apply((t) => ops.setScoreboardField(t, name, f, value))) {
      this.log.appendLine(`[actions] editScoreboard ${name}.${field} = ${raw || "(reset)"}`);
    }
  }

  /**
   * Proba whitebox (K2, felia 3) dintr-un net selectat in vederea-schema:
   * calea XMR (relativa la instanta DUT) si latimea vin din MODEL prin
   * `proposeProbe` (src/probe.ts, pur si testat); numele il confirma
   * utilizatorul. Refuzurile (bench de subsistem, tablou unpacked, interfata,
   * port deja mapat pe agent) vin tot de acolo, cu motivul afisat ca atare.
   */
  async createProbe(viewId: string | undefined, net: string): Promise<void> {
    if (!this.config.configUri) {
      return this.warnNoConfig();
    }
    const model = this.getModel();
    if (!model || !viewId || !net) {
      void vscode.window.showWarningMessage(
        vscode.l10n.t(
          "QuickUVM Architect: select a net in the schematic view first."
        )
      );
      return;
    }
    const check = proposeProbe(model, this.config.current, viewId, net);
    if (!check.ok) {
      void vscode.window.showWarningMessage(
        vscode.l10n.t("QuickUVM Architect: {0}", check.reason)
      );
      return;
    }
    const p = check.proposal;

    // Latimea: derivata din model cand se poate. Cand NU (toate capetele trec
    // prin select/concat), o cerem explicit — lasata implicita, QuickUVM face
    // proba de 1 bit si TRUNCHIAZA tacit un semnal lat.
    let width = p.width ?? undefined;
    if (width === undefined) {
      const raw = await vscode.window.showInputBox({
        title: vscode.l10n.t("Probe width (bits)"),
        value: "1",
        prompt: vscode.l10n.t(
          "the model cannot derive this net's width (its endpoints all go through select/concat) — left unset, QuickUVM would make it 1 bit and truncate"
        ),
        validateInput: (v) =>
          /^[1-9]\d*$/.test(v)
            ? undefined
            : vscode.l10n.t("a positive integer"),
      });
      if (!raw) {
        return;
      }
      width = Number(raw);
    }

    const taken = new Set(p.taken);
    const name = await vscode.window.showInputBox({
      title: vscode.l10n.t("Probe name"),
      value: Actions.uniqueName(p.name, taken),
      prompt: vscode.l10n.t("XMR path, relative to the DUT instance: {0}", p.path),
      validateInput: (v) =>
        !SV_IDENT_RE.test(v)
          ? vscode.l10n.t("invalid SystemVerilog identifier")
          : taken.has(v)
            ? vscode.l10n.t(
                "the name collides with another probe, an agent port/interface, the clock or the reset"
              )
            : undefined,
    });
    if (!name) {
      return;
    }

    // Coverage functional pe proba => `<dut>_probe_monitor` in env; gate-ul
    // anti-bug packaged (K2 #1) sta in probe.ts (pur, testat)
    let coverage = false;
    if (probeCoverageAllowed(this.config.current)) {
      const NO = vscode.l10n.t("$(eye) Observe only");
      const YES = vscode.l10n.t("$(graph) Also collect functional coverage");
      const pick = await vscode.window.showQuickPick([NO, YES], {
        title: vscode.l10n.t("Probe: functional coverage"),
      });
      if (!pick) {
        return;
      }
      coverage = pick === YES;
    }

    const w = width;
    if (
      await this.config.apply((t) =>
        ops.addProbe(t, { name, path: p.path, width: w, coverage })
      )
    ) {
      this.log.appendLine(
        `[actions] createProbe ${name} -> ${p.path} (${w}b${coverage ? ", coverage" : ""})`
      );
      if (await this.isComposedChild()) {
        void vscode.window.showWarningMessage(
          vscode.l10n.t(
            "QuickUVM Architect: this config is composed as a subenv of another bench. QuickUVM 0.9.2 generates the probe files but never wires them into the subsystem testbench — the probe only works when this block is generated standalone."
          )
        );
      }
    }
  }

  /**
   * Config-ul activ e referit ca `subenvs[].config` de un altul? Probele lui ar
   * fi generate, dar NU cablate in tb_top-ul subsistemului (fara instanta
   * probe_if, fara XMR, fara config_db, si nici macar in filelist) — bug real
   * al quick-uvm 0.9.2, care iese totusi cu 0: esec TACIT, deci avertizam.
   */
  private async isComposedChild(): Promise<boolean> {
    const uri = this.config.configUri;
    if (!uri) {
      return false;
    }
    const found = await vscode.workspace.findFiles(
      "**/*.quickuvm.yaml",
      "**/node_modules/**"
    );
    const files = await Promise.all(
      found.map(async (u) => ({
        path: u.fsPath,
        text: Buffer.from(await vscode.workspace.fs.readFile(u)).toString("utf8"),
      }))
    );
    // predicatul pur (yamlops, testat) compara caile normalizat — includes()
    // pe fsPath brut rata potrivirea la diferente de caz pe Windows
    return ops.isComposedChild(files, uri.fsPath);
  }

  /**
   * Derivă conexiunile inter-bloc H1 din net-urile vederii-schemă a
   * subsistemului și le scrie în `connections` (felia 3, „compunerea derivată").
   * Doar la subsistemul curent (config cu `subenvs`, dut = modulul vederii).
   * Blocurile DESTINAȚIE trebuie să aibă agent PASIV (`active: false`) — o
   * constrângere quick-uvm; se AVERTIZEAZĂ (nu se editează tăcut config-urile
   * copil, care sunt fișiere separate deținute de utilizator).
   */
  async wireConnections(viewId: string | undefined): Promise<void> {
    if (!this.config.configUri) {
      return this.warnNoConfig();
    }
    const model = this.getModel();
    const r = this.resolve(viewId);
    if (!model || !r) {
      return;
    }
    const cfg = this.config.current;
    if (cfg.dut?.name !== r.inst.module) {
      void vscode.window.showWarningMessage(
        vscode.l10n.t(
          "QuickUVM Architect: open the schematic of the subsystem DUT to wire its connections."
        )
      );
      return;
    }
    const subenvs = cfg.subenvs ?? [];
    if (!subenvs.length) {
      void vscode.window.showInformationMessage(
        vscode.l10n.t(
          "QuickUVM Architect: compose blocks as subenvs first (Create subenv)."
        )
      );
      return;
    }
    // rel-copil -> nume subenv, cu excluderea numelor ambigue: nucleul pur
    // subenvMapping (compose.ts, testat) — invariantul #3 al compunerii
    const mapping = subenvMapping(
      model,
      r.inst.path,
      subenvs.map((s) => s.name)
    );
    const derived = deriveConnections(model, r.inst.path, mapping.subenvOf);
    if (mapping.ambiguous.length) {
      derived.warnings.push(
        `ambiguous subenv names, not wired: ${mapping.ambiguous.join(", ")}`
      );
    }
    if (derived.connections.length === 0) {
      const msg = derived.warnings.length
        ? derived.warnings.join("; ")
        : vscode.l10n.t("no inter-block connections found among the composed blocks.");
      void vscode.window.showInformationMessage(
        vscode.l10n.t("QuickUVM Architect: {0}", msg)
      );
      return;
    }
    // Edit ATOMIC (un singur undo) pe MAI MULTE fisiere: `connections` pe top +
    // agentul blocului DESTINATIE pus pasiv in fiecare config-copil (un port de
    // intrare condus de fir nu poate fi si condus de propriul agent — quick-uvm
    // refuza altfel). Config-urile copil sunt fisiere separate; le editam
    // explicit (nu prin ConfigService.apply, care atinge doar config-ul activ).
    // Host-ul doar CITESTE fisierele; textele noi vin din planWireEdits
    // (compose.ts, pur, testat — inclusiv plierea pe fisier partajat, #4).
    const topUri = this.config.configUri;
    const dir = vscode.Uri.joinPath(topUri, "..");
    const fullRange = (d: vscode.TextDocument): vscode.Range =>
      new vscode.Range(d.positionAt(0), d.positionAt(d.getText().length));

    const topDoc = await vscode.workspace.openTextDocument(topUri);
    const topOld = topDoc.getText();
    const children = new Map<string, { key: string; text: string }>();
    const childDocs = new Map<string, vscode.TextDocument>();
    for (const sink of derived.sinks) {
      const config = subenvs.find((s) => s.name === sink)?.config;
      if (!config || children.has(config)) {
        continue;
      }
      const childUri = vscode.Uri.joinPath(dir, config);
      try {
        const doc = await vscode.workspace.openTextDocument(childUri);
        children.set(config, { key: childUri.toString(), text: doc.getText() });
        childDocs.set(childUri.toString(), doc);
      } catch {
        // fisier lipsa/ilizibil: planificatorul il pune la `manual`
      }
    }
    const plan = planWireEdits(topOld, subenvs, derived, children);
    const { passivated, manual } = plan;

    const edit = new vscode.WorkspaceEdit();
    if (plan.topText !== topOld) {
      edit.replace(topUri, fullRange(topDoc), plan.topText);
    }
    for (const [key, text] of plan.childTexts) {
      const doc = childDocs.get(key);
      if (doc) {
        edit.replace(doc.uri, fullRange(doc), text);
      }
    }

    if (!(await vscode.workspace.applyEdit(edit))) {
      void vscode.window.showErrorMessage(
        vscode.l10n.t("QuickUVM Architect: could not write the connections.")
      );
      return;
    }
    await this.config.refresh(); // sincron: `current` reflecta imediat noul YAML

    const parts = [
      vscode.l10n.t("{0} connection(s) wired", derived.connections.length),
    ];
    if (passivated.length) {
      parts.push(
        vscode.l10n.t("agents set passive: {0}", passivated.join(", "))
      );
    }
    if (manual.length) {
      // scheletul copilului n-are inca agent (createSubenv nu creeaza) sau
      // config-ul lipseste: utilizatorul configureaza agentul si-l face pasiv
      parts.push(
        vscode.l10n.t(
          "configure and passivate the agent for: {0}",
          manual.join(", ")
        )
      );
    }
    for (const w of derived.warnings) {
      parts.push(w);
    }
    void vscode.window.showInformationMessage(
      `QuickUVM Architect: ${parts.join(" — ")}`
    );
    this.log.appendLine(
      `[actions] wireConnections: ${derived.connections.length} conn, ` +
        `${passivated.length} passivated, ${manual.length} manual` +
        (derived.warnings.length ? `, ${derived.warnings.length} warnings` : "")
    );
  }

  /**
   * „Compose into parent bench" (felia 3): din vederea unui BLOC, compune blocul
   * + FRAȚII lui de bloc în bench-ul PĂRINTE imediat. Se reduce la `createSubenv`
   * țintind părintele (ensureDut recursiv + schelet + subenvs). Un subsistem cere
   * ≥2 subenv-uri (quick-uvm), deci se compun toți copiii-bloc ai părintelui;
   * utilizatorul confirmă lista în QuickPick-ul lui createSubenv.
   */
  async composeIntoParent(viewId: string | undefined): Promise<void> {
    const model = this.getModel();
    if (!model || !viewId) {
      return;
    }
    const pc = parentComposition(model, viewId);
    if (!pc) {
      void vscode.window.showInformationMessage(
        vscode.l10n.t(
          "QuickUVM Architect: this is a top-level module — it has no parent bench."
        )
      );
      return;
    }
    if (pc.childRels.length < 2) {
      // constrangere quick-uvm: un subsistem compune >=2 subenv-uri
      const parentModule =
        model.instances.find((i) => i.path === pc.parentPath)?.module ?? "?";
      void vscode.window.showWarningMessage(
        vscode.l10n.t(
          'QuickUVM Architect: the parent bench "{0}" has only {1} composable block(s) — a subsystem needs at least 2 subenvs.',
          parentModule,
          pc.childRels.length
        )
      );
      return;
    }
    // deleagă la createSubenv, ȚINTIND părintele (ensureDut + schelet + subenvs);
    // utilizatorul confirmă lista copiilor în QuickPick-ul lui createSubenv
    await this.createSubenv(pc.parentPath, pc.childRels);
  }

  /**
   * Drill în blocul compus (docs/05): deschide fișierul de config `configRel`
   * (calea din `subenvs[].config`, purtată de drill) cu editorul IMPLICIT al
   * `*.quickuvm.yaml` — adică diagrama TB per-fișier (felia 4). Calea vine de
   * la blocul chiar apăsat, deci nume duplicate deschid fișiere distincte.
   * Rezolvarea imită quick-uvm (pathlib): o cale ABSOLUTĂ e luată ca atare,
   * doar cea relativă se leagă de directorul config-ului curent. Merge pe
   * orice țintă TbEditTarget: config-ul activ (panel) sau documentul deschis
   * (editorul per-fișier — nesting-ul H1 pe niveluri).
   */
  async openSubenvConfig(
    configRel: string,
    cfg: TbEditTarget = this.config
  ): Promise<void> {
    const uri = cfg.configUri;
    if (!uri || !configRel) {
      return;
    }
    // cale absoluta: NU o lipi ca relativa (Uri.joinPath ar produce o cale
    // stricata — `/c:/proj/C:/abs/x.yaml`; quick-uvm o accepta ca atare)
    const child = path.isAbsolute(configRel)
      ? vscode.Uri.file(configRel)
      : vscode.Uri.joinPath(uri, "..", configRel);
    try {
      // editorul implicit al *.quickuvm.yaml e QuvmConfigEditor (felia 4)
      await vscode.commands.executeCommand("vscode.open", child);
    } catch {
      void vscode.window.showWarningMessage(
        vscode.l10n.t('QuickUVM Architect: cannot open "{0}".', configRel)
      );
    }
  }

  private warnNoConfig(): void {
    void vscode.window.showWarningMessage(
      vscode.l10n.t('QuickUVM Architect: no configuration exists yet — use "Set as DUT".')
    );
  }

  private warnNoAgents(): void {
    void vscode.window.showWarningMessage(
      vscode.l10n.t("QuickUVM Architect: the active configuration has no agents yet.")
    );
  }

  /**
   * Config activ cu dut == modulul vederii — cerinta subenv-urilor (docs/03).
   * Fara niciun config: fluxul Set as DUT (checkDut). Config activ pe ALT
   * dut: fluxul recursiv direct din gest — oferta explicita de config
   * dedicat blocului, apoi Set as DUT pe el; niciun buton mort.
   */
  private async ensureDutForView(inst: Instance): Promise<boolean> {
    const dut = this.config.current.dut?.name;
    if (dut === inst.module) {
      return true;
    }
    if (!dut) {
      return this.checkDut(inst);
    }
    const create = vscode.l10n.t(
      "Create {0}.quickuvm.yaml and set its DUT",
      inst.module
    );
    const pick = await vscode.window.showInformationMessage(
      vscode.l10n.t(
        'Agents and subenvs for "{0}" belong to its own config, but the active config targets "{1}" (recursive flow, docs/03).',
        inst.module,
        dut
      ),
      create
    );
    if (pick !== create) {
      return false;
    }
    if (!(await this.config.createConfigFor(inst.module))) {
      return false;
    }
    // config-ul nou e activ si fara dut: fluxul standard, fara intrebarea
    // de suprascriere (activeDut e acum undefined)
    await this.setDut(inst.path);
    return this.config.current.dut?.name === inst.module;
  }

  // ------------------------------------------------------- ignorePorts

  async ignorePorts(pinIds: string[], ignore: boolean): Promise<void> {
    const names = pinIds.map((id) => id.replace(/^<port>\./, ""));
    if (names.length === 0) {
      return;
    }
    await this.config.apply((t) =>
      ignore ? ops.ignorePorts(t, names) : ops.unignorePorts(t, names)
    );
  }

  async fixPortWidth(agent: string, port: string, width: number): Promise<void> {
    await this.config.apply((t) => ops.setAgentPortWidth(t, agent, port, width));
  }

  // ------------------------------------------------------------ intern

  /** Actiunile pe agenti cer un DUT setat si potrivit cu vederea curenta. */
  private async checkDut(inst: Instance): Promise<boolean> {
    const dut = this.config.current.dut?.name;
    if (!dut) {
      const pick = await vscode.window.showInformationMessage(
        vscode.l10n.t("QuickUVM Architect: no DUT is configured yet."),
        vscode.l10n.t("Set this module as DUT")
      );
      if (pick) {
        await this.setDut(inst.path);
        return Boolean(this.config.current.dut?.name);
      }
      return false;
    }
    if (dut !== inst.module) {
      void vscode.window.showWarningMessage(
        vscode.l10n.t(
          "QuickUVM Architect: the configured DUT is \"{0}\", but the current view shows \"{1}\". Open the DUT view or change the DUT.",
          dut,
          inst.module
        )
      );
      return false;
    }
    return true;
  }

  private async askAgentName(suggestion: string): Promise<string | undefined> {
    const existing = new Set(
      (this.config.current.agents ?? []).map((a) => a.name)
    );
    return vscode.window.showInputBox({
      title: vscode.l10n.t("Agent name"),
      value: suggestion,
      prompt: vscode.l10n.t(
        "SystemVerilog identifier; prefixes the generated files"
      ),
      validateInput: (v) =>
        !SV_IDENT_RE.test(v)
          ? vscode.l10n.t("invalid SystemVerilog identifier")
          : existing.has(v)
            ? vscode.l10n.t("an agent with this name already exists")
            : undefined,
    });
  }

  /** Instanta de interfata conectata la portul dat, prin vederea parintelui. */
  private connectedIface(
    model: ProjectModel,
    inst: Instance,
    portName: string,
    ifaceModule: string
  ): Instance | undefined {
    // parintele = cea mai lunga cale-instanta prefix propriu al caii curente
    let parent: Instance | undefined;
    for (const i of model.instances) {
      if (
        inst.path.startsWith(i.path + ".") &&
        (!parent || i.path.length > parent.path.length)
      ) {
        parent = i;
      }
    }
    if (parent) {
      const rel = inst.path.slice(parent.path.length + 1);
      const view = model.views[parent.path];
      const pin = view?.pins.find((p) => p.pin === `${rel}.${portName}`);
      if (pin?.conn && pin.conn.kind === "iface") {
        const base = pin.conn.ref.split(".")[0];
        const found = model.instances.find(
          (i) => i.path === `${parent.path}.${base}`
        );
        if (found?.iface) {
          return found;
        }
      }
    }
    // fallback: unica instanta a acelui tip de interfata din design
    const candidates = model.instances.filter(
      (i) => i.module === ifaceModule && i.iface
    );
    return candidates.length === 1 ? candidates[0] : undefined;
  }
}

/** `g_ch[0..2].u_ch` -> caile membrilor; un id fara pliaj ramane ca atare. */
function expandFold(rel: string): string[] {
  const m = /\[(\d+)\.\.(\d+)\]/.exec(rel);
  if (!m) {
    return [rel];
  }
  const out: string[] = [];
  for (let i = Number(m[1]); i <= Number(m[2]); i++) {
    out.push(rel.replace(m[0], `[${i}]`));
  }
  return out;
}

/** dut-ul euristic al unui bloc copil (scheletul din createSubenv, docs/03) */
function heuristicDut(module: string, def: ModuleDef | undefined): ops.DutSpec {
  const oneBitIns = (def?.ports ?? []).filter(
    (p) => p.dir === "in" && p.width === 1
  );
  const clock = oneBitIns.find((p) => CLOCK_RE.test(p.name))?.name ?? null;
  const reset = oneBitIns.find((p) => RESET_RE.test(p.name))?.name ?? null;
  return {
    module,
    clock,
    reset,
    resetActiveLow: reset ? ACTIVE_LOW_RE.test(reset) : true,
    externalReset: false,
    combinational: !clock,
  };
}

/** Sugestie de nume de agent din prefixul comun al pinilor selectati. */
export function suggestName(pinNames: string[]): string {
  const names = pinNames.map((n) => n.replace(/^<port>\./, ""));
  if (names.length === 1) {
    return names[0];
  }
  const first = names[0] ?? "agent";
  let prefix = first;
  for (const n of names) {
    while (prefix && !n.startsWith(prefix)) {
      prefix = prefix.slice(0, -1);
    }
  }
  prefix = prefix.replace(/_+$/, "");
  return SV_IDENT_RE.test(prefix) ? prefix : "agent1";
}
