// The QuickUVM configuration actions (docs/03): setDut with explicitly
// confirmed heuristics, agent from a pin selection (with the perspective
// inversion!), agent from an interface (unfolding the modport), ignoring
// ports. All produce YAML edits through ConfigService.apply (WorkspaceEdit).

import * as path from "path";
import * as vscode from "vscode";
import {
  deriveConnections,
  parentComposition,
  planWireEdits,
  subenvMapping,
  subenvName,
} from "./compose";
import { ConfigService, TbEditTarget } from "./config";
// the name-based heuristics (including the _ni/_bi pitfall) live in heuristics (pure, tested)
import { kindBlockers, layoutBlockers } from "./benchid";
import { coveredAgent, parseBinSpec, scoreboardEndpoints } from "./coverage";
import { ACTIVE_LOW_RE, CLOCK_RE, RESET_RE, SV_IDENT_RE } from "./heuristics";
import { Instance, ModuleDef, Port, ProjectModel } from "./model";
import { probeCoverageAllowed, proposeProbe } from "./probe";
import type { QuvmConfig } from "./quickuvm";
import * as ops from "./yamlops";

export class Actions {
  constructor(
    private readonly getModel: () => ProjectModel | undefined,
    private readonly config: ConfigService,
    private readonly log: vscode.OutputChannel
  ) {}

  private resolve(
    viewId: string | undefined
  ): { inst: Instance; def: ModuleDef } | undefined {
    const model = this.getModel();
    const inst = model?.instances.find((i) => i.path === viewId);
    const def = inst ? model?.modules[inst.module] : undefined;
    if (!inst || !def) {
      void vscode.window.showWarningMessage(
        vscode.l10n.t(
          "QuickUVM Architect: open the symbol view of an instance first."
        )
      );
      return undefined;
    }
    return { inst, def };
  }

  // ------------------------------------------------------------- setDut

  /** Designating the DUT with heuristic proposals, never applied silently. */
  async setDut(viewId: string | undefined): Promise<void> {
    const r = this.resolve(viewId);
    if (!r) {
      return;
    }
    const { inst, def } = r;
    const oneBitIns = def.ports.filter((p) => p.dir === "in" && p.width === 1);
    let clock = oneBitIns.find((p) => CLOCK_RE.test(p.name))?.name ?? null;
    const reset = oneBitIns.find((p) => RESET_RE.test(p.name))?.name ?? null;

    type Item = vscode.QuickPickItem & { id: string };
    const items: Item[] = [];
    if (clock) {
      items.push({
        id: "clock",
        label: vscode.l10n.t("$(watch) Clock: {0}", clock),
        detail: vscode.l10n.t("heuristic — uncheck if this is not the clock"),
        picked: true,
      });
    } else {
      items.push({
        id: "comb",
        label: vscode.l10n.t(
          "$(circuit-board) Combinational DUT (no clock of its own)"
        ),
        detail: vscode.l10n.t(
          "no clock candidate found; the testbench cadence remains"
        ),
        picked: true,
      });
    }
    if (reset) {
      const low = ACTIVE_LOW_RE.test(reset);
      items.push({
        id: "reset",
        label: vscode.l10n.t(
          "$(refresh) Reset: {0} (active on {1})",
          reset,
          low ? "0" : "1"
        ),
        picked: true,
      });
      items.push({
        id: "external",
        label: vscode.l10n.t(
          "$(plug) External reset (generated by the testbench, not by the agent)"
        ),
        picked: false,
      });
    }
    const picked = await vscode.window.showQuickPick(items, {
      canPickMany: true,
      title: vscode.l10n.t("Set as DUT: {0}", inst.module),
      placeHolder: vscode.l10n.t("Confirm the heuristic proposals (docs/03)"),
    });
    if (!picked) {
      return;
    }
    const has = (id: string) => picked.some((i) => i.id === id);

    if (clock && !has("clock")) {
      clock = null;
    }
    let combinational = !clock && (has("comb") || !items.some((i) => i.id === "comb"));
    if (!clock && !has("comb") && items.some((i) => i.id === "comb")) {
      // the user refuses combinational too: choose the clock manually
      const pick = await vscode.window.showQuickPick(
        oneBitIns.map((p) => p.name),
        { title: vscode.l10n.t("Choose the clock port") }
      );
      if (!pick) {
        return;
      }
      clock = pick;
      combinational = false;
    }

    const spec: ops.DutSpec = {
      module: inst.module,
      clock,
      reset: has("reset") && reset ? reset : null,
      resetActiveLow: reset ? ACTIVE_LOW_RE.test(reset) : true,
      externalReset: has("external"),
      combinational,
    };
    // active config on a DIFFERENT dut: explicit choice — overwrite the dut of
    // the active config (phase 2 semantics) or create the config dedicated to
    // the block (the recursive composition flow, docs/03); nothing silent
    const activeDut = this.config.current.dut?.name;
    let uri: vscode.Uri | undefined;
    if (activeDut && activeDut !== inst.module && this.config.configUri) {
      const overwrite = vscode.l10n.t(
        "Change the DUT of the active config ({0} → {1})",
        activeDut,
        inst.module
      );
      const fresh = vscode.l10n.t(
        "Create {0}.quickuvm.yaml for this block (subenv child config)",
        inst.module
      );
      const pick = await vscode.window.showQuickPick([fresh, overwrite], {
        title: vscode.l10n.t("Set as DUT: {0}", inst.module),
        placeHolder: vscode.l10n.t(
          'The active config targets "{0}" — choose what to do',
          activeDut
        ),
      });
      if (!pick) {
        return;
      }
      uri =
        pick === fresh
          ? await this.config.createConfigFor(inst.module)
          : await this.config.ensureConfig(inst.module);
    } else {
      uri = await this.config.ensureConfig(inst.module);
    }
    if (!uri) {
      return;
    }
    if (await this.config.apply((t) => ops.setDut(t, spec))) {
      this.log.appendLine(`[actions] setDut ${inst.module} -> ${uri.fsPath}`);
    }
  }

  // ------------------------------------------------- agent from selection

  /**
   * Agent from the selected pins. The YAML directions are from the DUT's
   * perspective (docs/03): the DUT inputs become `inputs` (the agent drives them), the outputs
   * `outputs` with randomize: false.
   */
  async createAgentFromPins(
    viewId: string | undefined,
    pinIds: string[]
  ): Promise<void> {
    const r = this.resolve(viewId);
    if (!r) {
      return;
    }
    const { inst, def } = r;
    if (!(await this.ensureDutForView(inst))) {
      return;
    }
    const names = pinIds
      .map((id) => id.replace(/^<port>\./, ""))
      .filter((n, i, all) => all.indexOf(n) === i);
    const ports = names
      .map((n) => def.ports.find((p) => p.name === n))
      .filter((p): p is Port => Boolean(p));
    if (ports.length === 0) {
      void vscode.window.showWarningMessage(
        vscode.l10n.t(
          "QuickUVM Architect: select the DUT pins for the agent first."
        )
      );
      return;
    }

    const roles = this.config.lastOverlay?.roles ?? {};
    const inputs: ops.AgentPortSpec[] = [];
    const outputs: ops.AgentPortSpec[] = [];
    const inouts: ops.AgentPortSpec[] = [];
    const skipped: string[] = [];

    for (const p of ports) {
      if (roles[p.name] === "clock" || roles[p.name] === "reset") {
        skipped.push(vscode.l10n.t("{0} (role {1})", p.name, roles[p.name]));
        continue;
      }
      // SV `ref` ports have no QuickUVM equivalent (the schema's port kinds are
      // inputs/outputs/inouts) — still skipped. `inout`, by contrast, maps to
      // `ports.inouts[]` (schema §1.5) and is routed below, not dropped.
      if (p.dir === "ref") {
        skipped.push(
          vscode.l10n.t("{0} (ref port — not a QuickUVM port concept)", p.name)
        );
        continue;
      }
      if (p.width === null) {
        skipped.push(vscode.l10n.t("{0} (no fixed size)", p.name));
        continue;
      }
      let width = p.width;
      if (p.unpacked_dims) {
        // unpacked array: explicit decision per port (docs/03)
        const flat = vscode.l10n.t("Flatten (width={0})", p.width);
        const choice = await vscode.window.showQuickPick(
          [flat, vscode.l10n.t("Exclude the port")],
          {
            title: vscode.l10n.t(
              "\"{0}\" is an unpacked array {1} × {2} bits — QuickUVM has no such notion",
              p.name,
              JSON.stringify(p.unpacked_dims),
              String(p.elem_width)
            ),
          }
        );
        if (!choice) {
          return;
        }
        if (choice !== flat) {
          skipped.push(vscode.l10n.t("{0} (unpacked array excluded)", p.name));
          continue;
        }
        width = p.width;
      }
      const bucket =
        p.dir === "in" ? inputs : p.dir === "inout" ? inouts : outputs;
      bucket.push({ name: p.name, width });
    }

    if (inputs.length + outputs.length + inouts.length === 0) {
      void vscode.window.showWarningMessage(
        vscode.l10n.t(
          "QuickUVM Architect: no usable pin in the selection ({0}).",
          skipped.join("; ")
        )
      );
      return;
    }

    const name = await this.askAgentName(suggestName(names));
    if (!name) {
      return;
    }
    const style = vscode.workspace
      .getConfiguration("quickuvm")
      .get<"manual" | "field_macros">("seqItemStyle", "manual");

    if (
      await this.config.apply((t) =>
        ops.createAgent(t, { name, inputs, outputs, inouts, seqItemStyle: style })
      )
    ) {
      // keep the main sentence stable; report inouts (and any exclusions) as an
      // optional parenthetical so the no-inout / no-exclusion case is unchanged
      const notes: string[] = [];
      if (inouts.length) {
        notes.push(vscode.l10n.t("{0} inouts", inouts.length));
      }
      if (skipped.length) {
        notes.push(vscode.l10n.t("excluded: {0}", skipped.join("; ")));
      }
      const note = notes.length ? ` (${notes.join("; ")})` : "";
      void vscode.window.showInformationMessage(
        vscode.l10n.t(
          "QuickUVM Architect: agent \"{0}\" with {1} inputs / {2} outputs{3}.",
          name,
          inputs.length,
          outputs.length,
          note
        )
      );
    }
  }

  // ------------------------------------------------ agent from interface

  /** Agent from the interface port: unfolds the DUT's modport (docs/03). */
  async createAgentFromIface(
    viewId: string | undefined,
    portName: string
  ): Promise<void> {
    const model = this.getModel();
    const r = this.resolve(viewId);
    if (!r || !model) {
      return;
    }
    const { inst, def } = r;
    if (!(await this.ensureDutForView(inst))) {
      return;
    }
    const ifp = def.iface_ports.find((p) => p.name === portName);
    if (!ifp) {
      return;
    }

    // the connected interface instance: through the parent's view, otherwise by type
    const ifaceInst = this.connectedIface(model, inst, portName, ifp.interface);
    if (!ifaceInst?.iface) {
      void vscode.window.showWarningMessage(
        vscode.l10n.t(
          "QuickUVM Architect: cannot find an instance of interface \"{0}\" with elaborated signals.",
          ifp.interface
        )
      );
      return;
    }
    const modportName = ifp.modport ?? "";
    const modport = ifaceInst.iface.modports[modportName];
    if (!modport) {
      void vscode.window.showWarningMessage(
        vscode.l10n.t(
          "QuickUVM Architect: interface \"{0}\" has no modport \"{1}\" in the model.",
          ifp.interface,
          modportName
        )
      );
      return;
    }

    const widths = new Map(
      ifaceInst.iface.signals.map((s) => [s.name, s.width])
    );
    const inputs: ops.AgentPortSpec[] = [];
    const outputs: ops.AgentPortSpec[] = [];
    const skipped: string[] = [];
    for (const [signal, dir] of Object.entries(modport)) {
      const width = widths.get(signal) ?? null;
      if (CLOCK_RE.test(signal) && width === 1) {
        skipped.push(vscode.l10n.t("{0} (interface clock -> dut.clock)", signal));
        continue;
      }
      if (width === null) {
        skipped.push(vscode.l10n.t("{0} (no fixed size)", signal));
        continue;
      }
      // the same perspective inversion: an `in` signal in the DUT's modport
      // => the DUT receives it => the agent drives it => inputs
      if (dir === "in") {
        inputs.push({ name: signal, width });
      } else if (dir === "out") {
        outputs.push({ name: signal, width });
      } else {
        skipped.push(vscode.l10n.t("{0} ({1} not supported)", signal, dir));
      }
    }
    if (inputs.length + outputs.length === 0) {
      void vscode.window.showWarningMessage(
        vscode.l10n.t(
          "QuickUVM Architect: modport \"{0}\" has no usable signals ({1}).",
          modportName,
          skipped.join("; ")
        )
      );
      return;
    }

    const name = await this.askAgentName(portName);
    if (!name) {
      return;
    }
    const style = vscode.workspace
      .getConfiguration("quickuvm")
      .get<"manual" | "field_macros">("seqItemStyle", "manual");
    if (
      await this.config.apply((t) =>
        ops.createAgent(t, { name, inputs, outputs, seqItemStyle: style })
      )
    ) {
      const note = skipped.length
        ? vscode.l10n.t(" (excluded: {0})", skipped.join("; "))
        : "";
      void vscode.window.showInformationMessage(
        vscode.l10n.t(
          "QuickUVM Architect: agent \"{0}\" from {1}.{2}{3}. The original SV interface remains the source of the specification; QuickUVM generates its own {0}_if.sv (known limitation, docs/03).",
          name,
          ifp.interface,
          modportName,
          note
        )
      );
    }
  }

  // ------------------------------------------------------ createSubenv

  /**
   * H1 subenvs from the blocks selected in the schematic view (docs/03): one
   * subenv per instance (the folds are unfolded into members), the child's config
   * `<modul>.quickuvm.yaml` next to the top config, created when needed with a skeleton +
   * heuristic dut; params with integer values only (the schema requires dict[str, int]).
   * The QuickUVM H1 constraints (children combinational only; params require
   * `parameters:` declared in the block's agent) are flagged in the confirmation.
   */
  async createSubenv(
    viewId: string | undefined,
    nodeIds: string[]
  ): Promise<void> {
    const model = this.getModel();
    const r = this.resolve(viewId);
    if (!r || !model) {
      return;
    }
    const { inst } = r;
    if (!(await this.ensureDutForView(inst))) {
      return;
    }
    const topUri = this.config.configUri;
    if (!topUri) {
      return;
    }

    // the selection -> child instances: the folds are unfolded, the interfaces are skipped
    const rels = [...new Set(nodeIds.flatMap(expandFold))];
    const targets: { rel: string; child: Instance }[] = [];
    for (const rel of rels) {
      const child = model.instances.find(
        (i) => i.path === `${inst.path}.${rel}`
      );
      if (child && !child.iface) {
        targets.push({ rel, child });
      }
    }
    if (targets.length === 0) {
      void vscode.window.showWarningMessage(
        vscode.l10n.t(
          "QuickUVM Architect: select one or more child blocks in the schematic view first."
        )
      );
      return;
    }

    // proposals: unique names; the subenvs already present in YAML are skipped
    const existing = new Set(
      (this.config.current.subenvs ?? [])
        .map((s) => s.name)
        .filter((n): n is string => Boolean(n))
    );
    const used = new Set(existing);
    const already: string[] = [];
    interface Proposal {
      name: string;
      rel: string;
      module: string;
      configFile: string;
      params: Record<string, number>;
      skippedParams: string[];
    }
    const proposals: Proposal[] = [];
    for (const { rel, child } of targets) {
      const base = subenvName(rel);
      if (existing.has(base)) {
        already.push(rel);
        continue;
      }
      let name = base;
      for (let n = 2; used.has(name); n++) {
        name = `${base}_${n}`;
      }
      used.add(name);
      const params: Record<string, number> = {};
      const skippedParams: string[] = [];
      for (const [k, v] of Object.entries(child.params)) {
        if (/^-?\d+$/.test(v.trim())) {
          params[k] = Number(v.trim());
        } else {
          skippedParams.push(`${k}=${v}`);
        }
      }
      proposals.push({
        name,
        rel,
        module: child.module,
        configFile: `${child.module}.quickuvm.yaml`,
        params,
        skippedParams,
      });
    }
    if (proposals.length === 0) {
      void vscode.window.showInformationMessage(
        vscode.l10n.t(
          "QuickUVM Architect: the selected blocks are already subenvs ({0}).",
          already.join(", ")
        )
      );
      return;
    }

    // the missing child configs: skeleton + heuristic dut, summarized in the confirmation
    const dir = vscode.Uri.joinPath(topUri, "..");
    const newConfigs = new Map<string, { uri: vscode.Uri; spec: ops.DutSpec }>();
    for (const p of proposals) {
      if (newConfigs.has(p.module)) {
        continue;
      }
      const uri = vscode.Uri.joinPath(dir, p.configFile);
      try {
        await vscode.workspace.fs.stat(uri);
      } catch {
        newConfigs.set(p.module, {
          uri,
          spec: heuristicDut(p.module, this.getModel()?.modules[p.module]),
        });
      }
    }

    type Item = vscode.QuickPickItem & { proposal: Proposal };
    const items: Item[] = proposals.map((p) => {
      const fresh = newConfigs.get(p.module);
      const notes: string[] = [];
      if (Object.keys(p.params).length) {
        notes.push(
          `params: {${Object.entries(p.params)
            .map(([k, v]) => `${k}: ${v}`)
            .join(", ")}}`
        );
      }
      if (p.skippedParams.length) {
        notes.push(
          vscode.l10n.t("non-integer params omitted: {0}",
            p.skippedParams.join(", "))
        );
      }
      if (fresh) {
        // children with a clock are accepted by the H1 composition from the M1
        // clocked-subenv slice (single-clock, at most one reset) — the heuristic
        // skeleton always satisfies the condition
        notes.push(
          fresh.spec.combinational
            ? vscode.l10n.t("new config (combinational DUT)")
            : vscode.l10n.t(
                "new config (clock: {0}, reset: {1})",
                fresh.spec.clock ?? "?",
                fresh.spec.reset ?? "—"
              )
        );
      }
      return {
        proposal: p,
        label: p.name,
        description: `${p.module} → ${p.configFile}`,
        detail: notes.join(" • ") || undefined,
        picked: true,
      };
    });
    const picked = await vscode.window.showQuickPick(items, {
      canPickMany: true,
      title: vscode.l10n.t("Create subenvs in {0}", inst.module),
      placeHolder: vscode.l10n.t(
        "Confirm the subenvs to add (docs/03); params require the block agent to declare `parameters:`"
      ),
    });
    if (!picked || picked.length === 0) {
      return;
    }

    // 1. the missing child configs, only for the confirmed modules
    const chosenModules = new Set(picked.map((i) => i.proposal.module));
    const creations = [...newConfigs.entries()].filter(([m]) =>
      chosenModules.has(m)
    );
    if (creations.length) {
      const edit = new vscode.WorkspaceEdit();
      for (const [module, c] of creations) {
        edit.createFile(c.uri, {
          ignoreIfExists: true,
          contents: Buffer.from(
            ops.setDut(ops.newConfigText(module), c.spec),
            "utf8"
          ),
        });
      }
      await vscode.workspace.applyEdit(edit);
      for (const [, c] of creations) {
        this.log.appendLine(`[actions] createSubenv: created ${c.uri.fsPath}`);
      }
    }

    // A bench that keeps its own agents AND composes subenvs is VALID in
    // QuickUVM 1.0 (assumption A9 lifted): the own agents become boundary agents
    // (H2), wired at the subsystem boundary — `createSubenvs` already preserves
    // them (it keeps the top clock only in this hybrid case). So there is no
    // rejection to guard against: we compose directly, no blocking modal.

    // 2. the subenvs entries into the top config (a single WorkspaceEdit)
    const specs: ops.SubenvSpec[] = picked.map((i) => ({
      name: i.proposal.name,
      config: i.proposal.configFile,
      params: i.proposal.params,
    }));
    if (await this.config.apply((t) => ops.createSubenvs(t, specs))) {
      const notes: string[] = [];
      if (creations.length) {
        notes.push(
          vscode.l10n.t(
            "{0} new block config(s) — configure their agents next (recursive flow, docs/03)",
            creations.length
          )
        );
      }
      if (already.length) {
        notes.push(
          vscode.l10n.t("already subenvs: {0}", already.join(", "))
        );
      }
      void vscode.window.showInformationMessage(
        vscode.l10n.t(
          "QuickUVM Architect: {0} subenv(s) added{1}.",
          specs.length,
          notes.length ? ` (${notes.join("; ")})` : ""
        )
      );
    }
  }

  // ------------------------------------ the verification view (3b, slice 2)

  /** the names of the agents from the active config */
  private agentNames(cfg: TbEditTarget, activeOnly = false): string[] {
    return (cfg.current.agents ?? [])
      .filter((a) => !activeOnly || a.active !== false)
      .map((a) => a.name)
      .filter((n): n is string => Boolean(n));
  }

  /** The clock-domain names of a bench: the `name` of each entry when `clock:` is
   *  a list (multi-domain, schema §1.4), else the single domain (`dut.clock` or the
   *  default `clk`). Used to offer a probe's sampling domain only when there is a
   *  real choice (>1 domain). */
  private static clockDomainNames(cfg: QuvmConfig): string[] {
    const clock = (cfg as { clock?: unknown }).clock;
    if (Array.isArray(clock)) {
      const names = clock.map((d) => {
        const n = d && typeof d === "object"
          ? (d as { name?: unknown }).name
          : undefined;
        return typeof n === "string" && n ? n : "clk";
      });
      return names.length ? names : ["clk"];
    }
    return [cfg.dut?.clock ?? "clk"];
  }

  /** a unique name for a new entry (`base`, then `base2`, `base3`…) */
  private static uniqueName(base: string, taken: Set<string>): string {
    if (!taken.has(base)) {
      return base;
    }
    for (let n = 2; ; n++) {
      const name = `${base}${n}`;
      if (!taken.has(name)) {
        return name;
      }
    }
  }

  /** Coverage collector for an agent (`analysis.coverage`, docs/03).
   *  `cfg` = the active config (panel) OR the open document (CustomTextEditor). */
  async addCoverage(preselect?: string, cfg: TbEditTarget = this.config): Promise<void> {
    if (!cfg.configUri) {
      return this.warnNoConfig();
    }
    const agents = this.agentNames(cfg);
    if (!agents.length) {
      return this.warnNoAgents();
    }
    // entries come in both forms (bare name / rich model) — docs/07 P3b
    const covered = new Set(
      (cfg.current.analysis?.coverage ?? []).map((c) => coveredAgent(c))
    );
    const choices = agents.filter((a) => !covered.has(a));
    if (!choices.length) {
      void vscode.window.showInformationMessage(
        vscode.l10n.t("QuickUVM Architect: every agent already has a coverage collector.")
      );
      return;
    }
    let agent = preselect && choices.includes(preselect) ? preselect : undefined;
    if (!agent) {
      agent = await vscode.window.showQuickPick(choices, {
        title: vscode.l10n.t("Coverage collector for agent"),
      });
      if (!agent) {
        return;
      }
    }
    const a = agent;
    if (await cfg.apply((t) => ops.addCoverage(t, a))) {
      this.log.appendLine(`[actions] addCoverage ${a}`);
    }
  }

  /** Scoreboard from the agents' streams (`analysis.scoreboards`, docs/03). */
  async addScoreboard(preselSource?: string, cfg: TbEditTarget = this.config): Promise<void> {
    if (!cfg.configUri) {
      return this.warnNoConfig();
    }
    // docs/07 P3c — on a composition the endpoints also include the children's agents
    // (`<subenv>.<agent>`), which is what makes a scoreboard cross-block. `childAgents`
    // is only tracked on the active config; a per-file editor target keeps its own.
    const agents = scoreboardEndpoints(
      this.agentNames(cfg),
      cfg === this.config ? this.config.childAgents : {}
    );
    if (!agents.length) {
      return this.warnNoAgents();
    }
    let source =
      preselSource && agents.includes(preselSource) ? preselSource : undefined;
    if (!source) {
      source = await vscode.window.showQuickPick(agents, {
        title: vscode.l10n.t("Scoreboard: stimulus/source agent"),
        placeHolder: vscode.l10n.t("the stream fed into the predictor"),
      });
      if (!source) {
        return;
      }
    }
    const src = source;
    const NONE = vscode.l10n.t("$(circle-slash) None (single-stream)");
    const monPick = await vscode.window.showQuickPick(
      [NONE, ...agents.filter((a) => a !== src)],
      {
        title: vscode.l10n.t("Scoreboard: response/monitor agent (A2 two-stream)"),
        placeHolder: vscode.l10n.t("the observed stream compared against the prediction"),
      }
    );
    if (monPick === undefined) {
      return;
    }
    const monitor = monPick === NONE ? undefined : monPick;

    let match: "in_order" | "out_of_order" = "in_order";
    let matchKey: string | undefined;
    if (monitor) {
      const IN = vscode.l10n.t("In order (FIFO pair)");
      const OOO = vscode.l10n.t("Out of order (keyed pool — a reordering DUT)");
      const mPick = await vscode.window.showQuickPick([IN, OOO], {
        title: vscode.l10n.t("Scoreboard: comparison strategy"),
      });
      if (!mPick) {
        return;
      }
      if (mPick === OOO) {
        match = "out_of_order";
        matchKey = await vscode.window.showInputBox({
          title: vscode.l10n.t("Match key (monitor transaction field)"),
          prompt: vscode.l10n.t("the field each response is keyed on (required for out-of-order)"),
          validateInput: (v) =>
            SV_IDENT_RE.test(v)
              ? undefined
              : vscode.l10n.t("invalid SystemVerilog identifier"),
        });
        if (!matchKey) {
          return;
        }
      }
    }

    const taken = new Set(
      (cfg.current.analysis?.scoreboards ?? [])
        .map((s) => s.name)
        .filter((n): n is string => Boolean(n))
    );
    const name = await vscode.window.showInputBox({
      title: vscode.l10n.t("Scoreboard name"),
      value: Actions.uniqueName("sbd", taken),
      validateInput: (v) =>
        !SV_IDENT_RE.test(v)
          ? vscode.l10n.t("invalid SystemVerilog identifier")
          : taken.has(v)
            ? vscode.l10n.t("a scoreboard with this name already exists")
            : undefined,
    });
    if (!name) {
      return;
    }
    if (
      await cfg.apply((t) =>
        ops.addScoreboard(t, { name, source: src, monitor, match, matchKey })
      )
    ) {
      this.log.appendLine(
        `[actions] addScoreboard ${name} (${src}${monitor ? ` vs ${monitor}` : ""})`
      );
    }
  }

  /** Virtual sequence coordinating the sequencers of the active agents (C2, docs/03). */
  async addVirtualSequence(cfg: TbEditTarget = this.config): Promise<void> {
    if (!cfg.configUri) {
      return this.warnNoConfig();
    }
    const active = this.agentNames(cfg, true);
    if (!active.length) {
      void vscode.window.showWarningMessage(
        vscode.l10n.t("QuickUVM Architect: a virtual sequence needs at least one active agent.")
      );
      return;
    }
    const taken = new Set(
      (cfg.current.virtual_sequences ?? [])
        .map((v) => v.name)
        .filter((n): n is string => Boolean(n))
    );
    const name = await vscode.window.showInputBox({
      title: vscode.l10n.t("Virtual sequence name"),
      value: Actions.uniqueName("vseq", taken),
      validateInput: (v) =>
        !SV_IDENT_RE.test(v)
          ? vscode.l10n.t("invalid SystemVerilog identifier")
          : taken.has(v)
            ? vscode.l10n.t("a virtual sequence with this name already exists")
            : undefined,
    });
    if (!name) {
      return;
    }
    const picked =
      active.length === 1
        ? active
        : await vscode.window.showQuickPick(
            active.map((a) => ({ label: a, picked: true })),
            {
              canPickMany: true,
              title: vscode.l10n.t("Virtual sequence: agents to coordinate"),
            }
          ).then((sel) => sel?.map((i) => i.label));
    if (!picked || picked.length === 0) {
      return;
    }
    const SEQ = vscode.l10n.t("Sequential");
    const PAR = vscode.l10n.t("Parallel (fork…join)");
    const modePick =
      picked.length === 1
        ? SEQ
        : await vscode.window.showQuickPick([SEQ, PAR], {
            title: vscode.l10n.t("Virtual sequence: run mode"),
          });
    if (!modePick) {
      return;
    }
    const spec: ops.VseqSpec = {
      name,
      mode: modePick === PAR ? "parallel" : "sequential",
      steps: picked.map((a) => ({ agent: a, sequence: `${a}_seq` })),
    };
    if (await cfg.apply((t) => ops.addVirtualSequence(t, spec))) {
      this.log.appendLine(`[actions] addVirtualSequence ${name} (${picked.join(", ")})`);
    }
  }

  /**
   * Deletes a component of the verification environment (slice 2), with a MODAL
   * confirmation. Scoreboard/coverage/vseq are leaves (no one references them). For
   * an AGENT, the confirmation summarizes the cascade (its coverage, the scoreboards with
   * source/monitor == agent, the vseq steps) — the `removeAgent` mutation executes it.
   */
  async deleteComponent(
    kind: string,
    name: string,
    cfg: TbEditTarget = this.config
  ): Promise<void> {
    if (!cfg.configUri) {
      return this.warnNoConfig();
    }
    if (!name) {
      return;
    }
    let label: string;
    let detail: string | undefined;
    let mutate: (t: string) => string;
    switch (kind) {
      case "scoreboard":
        label = vscode.l10n.t('scoreboard "{0}"', name);
        mutate = (t) => ops.removeScoreboard(t, name);
        break;
      case "coverage":
        label = vscode.l10n.t('the coverage collector for "{0}"', name);
        mutate = (t) => ops.removeCoverage(t, name);
        break;
      case "vseq":
        label = vscode.l10n.t('virtual sequence "{0}"', name);
        mutate = (t) => ops.removeVirtualSequence(t, name);
        break;
      case "probe":
        label = vscode.l10n.t('probe "{0}"', name);
        mutate = (t) => ops.removeProbe(t, name);
        break;
      case "agent": {
        label = vscode.l10n.t('agent "{0}"', name);
        const cascade = this.agentCascade(name, cfg);
        if (cascade.length) {
          detail = vscode.l10n.t("This also removes: {0}.", cascade.join(", "));
        }
        mutate = (t) => ops.removeAgent(t, name);
        break;
      }
      default:
        return;
    }
    const DELETE = vscode.l10n.t("Delete");
    const pick = await vscode.window.showWarningMessage(
      vscode.l10n.t("Delete {0}?", label),
      { modal: true, detail },
      DELETE
    );
    if (pick !== DELETE) {
      return;
    }
    if (await cfg.apply(mutate)) {
      this.log.appendLine(`[actions] deleteComponent ${kind} ${name}`);
    }
  }

  /** The summary of what falls when an agent is deleted, for the modal confirmation. */
  private agentCascade(name: string, target: TbEditTarget): string[] {
    const cfg = target.current;
    const out: string[] = [];
    if ((cfg.analysis?.coverage ?? []).some((c) => coveredAgent(c) === name)) {
      out.push(vscode.l10n.t("its coverage collector"));
    }
    for (const s of cfg.analysis?.scoreboards ?? []) {
      if (s.source === name || s.monitor === name) {
        out.push(vscode.l10n.t('scoreboard "{0}"', s.name ?? "?"));
      }
    }
    for (const v of cfg.virtual_sequences ?? []) {
      const body = v.body ?? [];
      if (!body.some((st) => st.agent === name)) {
        continue;
      }
      // the sequence disappears only if ALL steps belong to the agent
      out.push(
        body.every((st) => st.agent === name)
          ? vscode.l10n.t('virtual sequence "{0}"', v.name ?? "?")
          : vscode.l10n.t('a step in "{0}"', v.name ?? "?")
      );
    }
    return out;
  }

  // ------------------------------ bench-level configuration (docs/07 line 3, P2)

  /**
   * Clock-domain authoring (docs/07 P4). `add` needs a domain name (prompted, since
   * a fresh domain has no port to name it after); the rest carry theirs. A list is a
   * different generation mode from a mapping, so the add/collapse conversions are
   * deliberate, and a removal blocked by an agent using the domain is reported.
   */
  async editClock(
    op: string,
    args: { name?: string; field?: string; value?: string },
    cfg: TbEditTarget = this.config
  ): Promise<void> {
    if (!cfg.configUri) {
      return;
    }
    try {
      let done = false;
      switch (op) {
        case "add": {
          const taken = new Set(
            (Array.isArray(cfg.current.clock) ? cfg.current.clock : [])
              .map((d) => (d as { name?: string }).name)
              .filter(Boolean)
          );
          taken.add(cfg.current.dut?.clock || "clk");
          const name = await vscode.window.showInputBox({
            title: vscode.l10n.t("New clock domain"),
            value: "sck",
            validateInput: (v) =>
              !SV_IDENT_RE.test(v)
                ? vscode.l10n.t("SV identifier")
                : taken.has(v)
                  ? vscode.l10n.t("a clock domain with this name already exists")
                  : undefined,
          });
          if (!name) {
            return;
          }
          done = await cfg.apply((t) => ops.addClockDomain(t, name));
          break;
        }
        case "remove":
          done = await cfg.apply((t) => ops.removeClockDomain(t, args.name ?? ""));
          break;
        case "collapse":
          done = await cfg.apply((t) => ops.collapseClocks(t));
          break;
        case "set": {
          const f = args.field as ops.ClockField;
          let value: string | number | undefined = args.value ?? "";
          if (value === "") {
            value = undefined;
          } else if (f === "period" || f === "drive_offset_pct") {
            const n = Number(value);
            if (!Number.isInteger(n) || n < 1) {
              return;
            }
            value = n;
          }
          done = await cfg.apply((t) =>
            ops.setClockDomainField(t, args.name ?? "", f, value)
          );
          break;
        }
        default:
          return;
      }
      if (done) {
        this.log.appendLine(`[actions] editClock ${op} ${args.name ?? ""}`);
      }
    } catch (e) {
      void vscode.window.showWarningMessage(
        vscode.l10n.t("QuickUVM Architect: {0}", (e as Error).message)
      );
    }
  }

  /**
   * Consume an agent BY REFERENCE from a separately generated VIP (docs/07 P5, F2').
   * The user picks a `.qvip` manifest; we read the agents it ships and add a
   * `{name, from_vip}` entry with the path RELATIVE to the consuming config, which is
   * how QuickUVM resolves it. The agent's own source is never regenerated — the VIP's
   * package filelist is chained instead.
   */
  async addVipAgent(cfg: TbEditTarget = this.config): Promise<void> {
    if (!cfg.configUri) {
      return this.warnNoConfig();
    }
    const picked = await vscode.window.showOpenDialog({
      title: vscode.l10n.t("Consume a VIP agent"),
      openLabel: vscode.l10n.t("Use VIP"),
      canSelectMany: false,
      filters: { "QuickUVM VIP manifest": ["qvip"] },
    });
    const manifest = picked?.[0];
    if (!manifest) {
      return;
    }
    let agents: string[] = [];
    try {
      const doc = await vscode.workspace.openTextDocument(manifest);
      const parsed = ops.parseQuvm(doc.getText()) as unknown as {
        agents?: Record<string, unknown>;
      };
      agents = Object.keys(parsed.agents ?? {});
    } catch {
      agents = [];
    }
    if (!agents.length) {
      void vscode.window.showWarningMessage(
        vscode.l10n.t(
          "QuickUVM Architect: {0} ships no agents — generate the VIP first (kind: vip).",
          path.basename(manifest.fsPath)
        )
      );
      return;
    }
    const taken = new Set(this.agentNames(cfg));
    const free = agents.filter((a) => !taken.has(a));
    if (!free.length) {
      void vscode.window.showWarningMessage(
        vscode.l10n.t(
          "QuickUVM Architect: this bench already has an agent named {0}.",
          agents.join(", ")
        )
      );
      return;
    }
    const name =
      free.length === 1
        ? free[0]
        : await vscode.window.showQuickPick(free, {
            title: vscode.l10n.t("VIP agent to consume"),
          });
    if (!name) {
      return;
    }
    // relative to the CONSUMING config — QuickUVM resolves `from_vip` from there
    const rel = path
      .relative(path.dirname(cfg.configUri.fsPath), manifest.fsPath)
      .split(path.sep)
      .join("/");
    if (await cfg.apply((t) => ops.addVipAgent(t, name, rel))) {
      this.log.appendLine(`[actions] addVipAgent ${name} from ${rel}`);
    }
  }

  /**
   * Sets a subenv's `namespace` (docs/07 P5). Absent is AUTO: QuickUVM prefixes an
   * instance's classes only when the same config is composed twice or more, so a
   * block used once stays byte-identical. `custom` asks for the prefix.
   */
  async editSubenvNamespace(
    subenv: string,
    mode: string,
    cfg: TbEditTarget = this.config
  ): Promise<void> {
    if (!cfg.configUri || !subenv) {
      return;
    }
    let value: boolean | string | undefined;
    if (mode === "auto") {
      value = undefined;
    } else if (mode === "on") {
      value = true;
    } else if (mode === "off") {
      value = false;
    } else if (mode === "custom") {
      const prefix = await vscode.window.showInputBox({
        title: vscode.l10n.t("Class-name prefix for {0}", subenv),
        value: subenv,
        validateInput: (v) =>
          SV_IDENT_RE.test(v) ? undefined : vscode.l10n.t("SV identifier"),
      });
      if (!prefix) {
        return;
      }
      value = prefix;
    } else {
      return;
    }
    try {
      if (await cfg.apply((t) => ops.setSubenvNamespace(t, subenv, value))) {
        this.log.appendLine(`[actions] editSubenvNamespace ${subenv} = ${mode}`);
      }
    } catch (e) {
      void vscode.window.showWarningMessage(
        vscode.l10n.t("QuickUVM Architect: {0}", (e as Error).message)
      );
    }
  }

  /**
   * Per-port depth on an agent (docs/07 P4c). `width` routes to the existing
   * `setAgentPortWidth` (the diagram's pin gesture uses it too, so there is one
   * width path); everything else goes through `setAgentPortField`, which enforces
   * the open-drain/pullup pair and the exclusive type specifiers.
   */
  async editAgentPort(
    args: { agent?: string; port?: string; field?: string; value?: string },
    cfg: TbEditTarget = this.config
  ): Promise<void> {
    const agent = args.agent ?? "";
    const port = args.port ?? "";
    if (!cfg.configUri || !agent || !port) {
      return;
    }
    const raw = args.value ?? "";
    try {
      if (args.field === "width") {
        const n = Number(raw);
        if (!Number.isInteger(n) || n < 1) {
          return;
        }
        if (await cfg.apply((t) => ops.setAgentPortWidth(t, agent, port, n))) {
          this.log.appendLine(`[actions] editAgentPort ${agent}.${port}.width = ${n}`);
        }
        return;
      }
      const fields: ops.PortField[] = [
        "randomize",
        "constraint",
        "open_drain",
        "pullup",
        "enum",
        "type",
      ];
      if (!fields.includes(args.field as ops.PortField)) {
        return;
      }
      const f = args.field as ops.PortField;
      let value: string | boolean | Record<string, number> | undefined;
      if (f === "randomize" || f === "open_drain" || f === "pullup") {
        value = raw === "true";
      } else if (f === "enum") {
        // `NAME=value, NAME=value` — the editor's one-line form for a symbolic field
        const map: Record<string, number> = {};
        for (const pair of raw.split(",")) {
          const [k, v] = pair.split("=");
          if (!k?.trim()) {
            continue;
          }
          const n = Number(v?.trim());
          if (!SV_IDENT_RE.test(k.trim()) || !Number.isInteger(n)) {
            void vscode.window.showWarningMessage(
              vscode.l10n.t(
                "QuickUVM Architect: an enum is `NAME=value` pairs, e.g. IDLE=0, BUSY=1."
              )
            );
            return;
          }
          map[k.trim()] = n;
        }
        value = map;
      } else {
        value = raw === "" ? undefined : raw;
      }
      if (await cfg.apply((t) => ops.setAgentPortField(t, agent, port, f, value))) {
        this.log.appendLine(`[actions] editAgentPort ${agent}.${port}.${f} = ${raw || "(reset)"}`);
      }
    } catch (e) {
      // the open-drain/pullup pair and the exclusive specifiers are reported, not written
      void vscode.window.showWarningMessage(
        vscode.l10n.t("QuickUVM Architect: {0}", (e as Error).message)
      );
    }
  }

  /**
   * Reset-domain authoring (docs/07 P4b). Mirrors `editClock`, with the two extra
   * invariants resets carry: under a LIST `dut.reset` names a declared DOMAIN, and
   * the single mapping's `external` flag has no list equivalent — the ops refuse the
   * lossy conversions and the reasons are shown.
   */
  async editReset(
    op: string,
    args: { name?: string; field?: string; value?: string },
    cfg: TbEditTarget = this.config
  ): Promise<void> {
    if (!cfg.configUri) {
      return;
    }
    try {
      let done = false;
      switch (op) {
        case "add": {
          const taken = new Set(
            (Array.isArray(cfg.current.reset) ? cfg.current.reset : [])
              .map((d) => (d as { name?: string }).name)
              .filter(Boolean)
          );
          taken.add(cfg.current.dut?.reset || "rst_n");
          const name = await vscode.window.showInputBox({
            title: vscode.l10n.t("New reset domain"),
            value: "srst_n",
            validateInput: (v) =>
              !SV_IDENT_RE.test(v)
                ? vscode.l10n.t("SV identifier")
                : taken.has(v)
                  ? vscode.l10n.t("a reset domain with this name already exists")
                  : undefined,
          });
          if (!name) {
            return;
          }
          done = await cfg.apply((t) => ops.addResetDomain(t, name));
          break;
        }
        case "remove":
          done = await cfg.apply((t) => ops.removeResetDomain(t, args.name ?? ""));
          break;
        case "collapse":
          done = await cfg.apply((t) => ops.collapseResets(t));
          break;
        case "set": {
          const f = args.field as ops.ResetField;
          const raw = args.value ?? "";
          const value: string | boolean | undefined =
            f === "active_low" || f === "external"
              ? raw === "true"
              : raw === ""
                ? undefined
                : raw;
          done = await cfg.apply((t) => ops.setResetDomainField(t, args.name ?? "", f, value));
          break;
        }
        default:
          return;
      }
      if (done) {
        this.log.appendLine(`[actions] editReset ${op} ${args.name ?? ""}`);
      }
    } catch (e) {
      void vscode.window.showWarningMessage(
        vscode.l10n.t("QuickUVM Architect: {0}", (e as Error).message)
      );
    }
  }

  /**
   * Rich functional-coverage authoring (docs/07 P3b). One entry point for every
   * gesture of the nested editor, so the webview needs a single message: `op` selects
   * the mutation, the rest are its arguments. Each op maps to a yamlops function that
   * edits the entry IN PLACE — hand-written keys the editor does not author
   * (illegal_bins, transitions, cross bins) are never rewritten away.
   */
  async editCoverage(
    op: string,
    args: { agent?: string; field?: string; bin?: string; spec?: string; fields?: string[]; value?: string },
    cfg: TbEditTarget = this.config
  ): Promise<void> {
    const agent = args.agent ?? "";
    if (!cfg.configUri || !agent) {
      return;
    }
    const field = args.field ?? "";
    try {
      let done = false;
      switch (op) {
        case "upgrade":
          done = await cfg.apply((t) => ops.upgradeCoverage(t, agent, field));
          break;
        case "downgrade": {
          const go = await vscode.window.showWarningMessage(
            vscode.l10n.t(
              "Drop the covergroup content for {0}? The agent keeps its coverage collector, but the coverpoints, bins and crosses go.",
              agent
            ),
            { modal: true },
            vscode.l10n.t("Drop")
          );
          if (!go) {
            return;
          }
          done = await cfg.apply((t) => ops.downgradeCoverage(t, agent));
          break;
        }
        case "addCoverpoint":
          done = await cfg.apply((t) => ops.addCoverpoint(t, agent, field));
          break;
        case "removeCoverpoint":
          done = await cfg.apply((t) => ops.removeCoverpoint(t, agent, field));
          break;
        case "setBin": {
          const spec = parseBinSpec(args.spec ?? "");
          if (!spec || !args.bin) {
            void vscode.window.showWarningMessage(
              vscode.l10n.t(
                "QuickUVM Architect: a bin is one value (5), an inclusive range (0..7) or a list (1, 2, 3)."
              )
            );
            return;
          }
          done = await cfg.apply((t) =>
            ops.setCoverageBin(t, agent, field, args.bin as string, spec)
          );
          break;
        }
        case "removeBin":
          done = await cfg.apply((t) =>
            ops.removeCoverageBin(t, agent, field, args.bin ?? "")
          );
          break;
        case "addCross":
          done = await cfg.apply((t) => ops.addCross(t, agent, args.fields ?? []));
          break;
        case "removeCross":
          done = await cfg.apply((t) => ops.removeCross(t, agent, args.value ?? ""));
          break;
        case "goal": {
          const raw = args.value ?? "";
          const goal = raw === "" ? undefined : Number(raw);
          done = await cfg.apply((t) => ops.setCoverageGoal(t, agent, goal));
          break;
        }
        default:
          return;
      }
      if (done) {
        this.log.appendLine(`[actions] editCoverage ${op} ${agent}${field ? "." + field : ""}`);
      }
    } catch (e) {
      // the couplings QuickUVM enforces (one coverpoint per field, >= 1 coverpoint,
      // goal is a percent) are reported rather than written and rejected later
      void vscode.window.showWarningMessage(
        vscode.l10n.t("QuickUVM Architect: {0}", (e as Error).message)
      );
    }
  }

  /** Adds a test to `tests[]` (docs/07 P2); the name is confirmed by the user. */
  async addTest(cfg: TbEditTarget = this.config): Promise<void> {
    if (!cfg.configUri) {
      return this.warnNoConfig();
    }
    const taken = new Set((cfg.current.tests ?? []).map((t) => t.name));
    const name = await vscode.window.showInputBox({
      title: vscode.l10n.t("New test"),
      value: `${cfg.current.dut?.name ?? "dut"}_test`,
      validateInput: (v) =>
        !SV_IDENT_RE.test(v)
          ? vscode.l10n.t("SV identifier")
          : taken.has(v)
            ? vscode.l10n.t("a test with this name already exists")
            : undefined,
    });
    if (!name) {
      return;
    }
    if (await cfg.apply((t) => ops.addTest(t, name))) {
      this.log.appendLine(`[actions] addTest ${name}`);
    }
  }

  /**
   * Removes a test. Removing the LAST one drops the whole `tests:` key, and the bench
   * falls back to QuickUVM's default `test1` — the user is told, because the
   * alternative (`tests: []`) is accepted and yields a bench with nothing to run.
   */
  async removeTest(name: string, cfg: TbEditTarget = this.config): Promise<void> {
    if (!cfg.configUri || !name) {
      return;
    }
    const last = (cfg.current.tests ?? []).length <= 1;
    const go = await vscode.window.showWarningMessage(
      last
        ? vscode.l10n.t(
            "Remove the last test ({0})? The bench falls back to QuickUVM's default test1 — it is never left without a test.",
            name
          )
        : vscode.l10n.t("Remove the test {0}?", name),
      { modal: true },
      vscode.l10n.t("Remove")
    );
    if (!go) {
      return;
    }
    if (await cfg.apply((t) => ops.removeTest(t, name))) {
      this.log.appendLine(`[actions] removeTest ${name}${last ? " (last)" : ""}`);
    }
  }

  /** Edits one field of a test (`num_items`, `seeds`, `vseq`); empty ⇒ default. */
  async editTest(
    name: string,
    field: string,
    raw: string,
    cfg: TbEditTarget = this.config
  ): Promise<void> {
    if (!cfg.configUri || !name) {
      return;
    }
    const fields: ops.TestField[] = ["num_items", "seeds", "vseq"];
    if (!fields.includes(field as ops.TestField)) {
      return;
    }
    const f = field as ops.TestField;
    let value: string | number | undefined;
    if (raw === "") {
      value = undefined;
    } else if (f === "num_items" || f === "seeds") {
      const n = Number(raw);
      if (!Number.isInteger(n) || n < (f === "seeds" ? 1 : 0)) {
        return;
      }
      value = n;
    } else {
      value = raw;
    }
    try {
      if (await cfg.apply((t) => ops.setTestField(t, name, f, value))) {
        this.log.appendLine(`[actions] editTest ${name}.${field} = ${raw || "(reset)"}`);
      }
    } catch (e) {
      // e.g. `seeds` with no `regress:` block — refused rather than written
      void vscode.window.showWarningMessage(
        vscode.l10n.t("QuickUVM Architect: {0}", (e as Error).message)
      );
    }
  }

  /**
   * Edits the bench identity (`layout`, `kind`, `top_name`, `auto_vseq_mode`,
   * `auto_virtual_sequences`) or a `project:` metadata field.
   *
   * `layout` and `kind` are GUARDED: each has hard prerequisites in QuickUVM
   * (subenvs need packaged, C3 instances need flat, a VIP drops every bench-layer
   * section), so a blocked switch is reported instead of written — `benchid.ts`
   * computes the reasons, and the panel already disables the option.
   */
  async editBench(
    field: string,
    raw: string,
    cfg: TbEditTarget = this.config
  ): Promise<void> {
    if (!cfg.configUri) {
      return;
    }
    const projectFields: ops.ProjectField[] = [
      "name",
      "author",
      "year",
      "uvm_version",
      "version",
    ];
    if (field.startsWith("project.")) {
      const pf = field.slice("project.".length) as ops.ProjectField;
      if (!projectFields.includes(pf)) {
        return;
      }
      const value = raw === "" ? undefined : pf === "year" ? Number(raw) : raw;
      if (pf === "year" && raw !== "" && !Number.isInteger(value)) {
        return;
      }
      try {
        if (await cfg.apply((t) => ops.setProjectField(t, pf, value))) {
          this.log.appendLine(`[actions] editBench project.${pf} = ${raw || "(reset)"}`);
        }
      } catch (e) {
        void vscode.window.showWarningMessage(
          vscode.l10n.t("QuickUVM Architect: {0}", (e as Error).message)
        );
      }
      return;
    }
    const fields: ops.BenchField[] = [
      "layout",
      "kind",
      "top_name",
      "auto_vseq_mode",
      "auto_virtual_sequences",
    ];
    if (!fields.includes(field as ops.BenchField)) {
      return;
    }
    const f = field as ops.BenchField;
    const blockers =
      f === "layout"
        ? layoutBlockers(cfg.current, raw as "flat" | "packaged")
        : f === "kind"
          ? kindBlockers(cfg.current, raw as "bench" | "vip" | "selftest")
          : [];
    if (blockers.length) {
      void vscode.window.showWarningMessage(
        vscode.l10n.t("QuickUVM Architect: {0}", blockers.join(" · "))
      );
      return;
    }
    const value = f === "auto_virtual_sequences" ? raw === "true" : raw;
    if (await cfg.apply((t) => ops.setBenchField(t, f, value))) {
      this.log.appendLine(`[actions] editBench ${field} = ${raw}`);
    }
  }

  /**
   * Enables RAL mode: creates the `register_model:` block (docs/07 P2). Its three
   * required fields are asked for up front — QuickUVM refuses a partial block, and
   * the RAL package itself is user-provided input the extension cannot infer.
   * `bus_agent` is offered over the INITIATOR agents only (a responder cannot carry
   * register traffic), which is also QuickUVM's own rule.
   */
  async addRegisterModel(cfg: TbEditTarget = this.config): Promise<void> {
    if (!cfg.configUri) {
      return this.warnNoConfig();
    }
    const initiators = (cfg.current.agents ?? [])
      .filter((a) => a.mode !== "responder" && a.name)
      .map((a) => a.name as string);
    if (!initiators.length) {
      void vscode.window.showWarningMessage(
        vscode.l10n.t(
          "QuickUVM Architect: a register model needs an initiator agent to carry the bus traffic — create one first."
        )
      );
      return;
    }
    const pkg = await vscode.window.showInputBox({
      title: vscode.l10n.t("Register model: RAL package"),
      prompt: vscode.l10n.t(
        "the external RAL package (user-provided input — QuickUVM consumes it, it does not generate it)"
      ),
      value: `${cfg.current.project?.name ?? cfg.current.dut?.name ?? "dut"}_ral_pkg`,
      validateInput: (v) => (SV_IDENT_RE.test(v) ? undefined : vscode.l10n.t("SV identifier")),
    });
    if (!pkg) {
      return;
    }
    const block = await vscode.window.showInputBox({
      title: vscode.l10n.t("Register model: uvm_reg_block class"),
      prompt: vscode.l10n.t("the register block class inside that package"),
      value: `${cfg.current.project?.name ?? cfg.current.dut?.name ?? "dut"}_reg_block`,
      validateInput: (v) => (SV_IDENT_RE.test(v) ? undefined : vscode.l10n.t("SV identifier")),
    });
    if (!block) {
      return;
    }
    const busAgent =
      initiators.length === 1
        ? initiators[0]
        : await vscode.window.showQuickPick(initiators, {
            title: vscode.l10n.t("Register model: bus agent"),
            placeHolder: vscode.l10n.t("the initiator whose driver the adapter talks through"),
          });
    if (!busAgent) {
      return;
    }
    if (
      await cfg.apply((t) =>
        ops.addRegisterModel(t, { package: pkg, block, bus_agent: busAgent })
      )
    ) {
      this.log.appendLine(`[actions] addRegisterModel ${pkg}.${block} via ${busAgent}`);
    }
  }

  /** Leaves RAL mode: deletes the whole `register_model:` block, after confirming —
   *  it also drops the generated adapter/reg-test files and their env wiring. */
  async removeRegisterModel(cfg: TbEditTarget = this.config): Promise<void> {
    if (!cfg.configUri || !cfg.current.register_model) {
      return;
    }
    const go = await vscode.window.showWarningMessage(
      vscode.l10n.t(
        "Remove the register model? The generated adapter, the CSR tests and their env wiring go with it."
      ),
      { modal: true },
      vscode.l10n.t("Remove")
    );
    if (!go) {
      return;
    }
    if (await cfg.apply((t) => ops.removeRegisterModel(t))) {
      this.log.appendLine("[actions] removeRegisterModel");
    }
  }

  /** Edits one `register_model:` field from the settings panel; empty ⇒ default.
   *  `csr_tests` arrives as a comma-separated list (the multiselect's value). */
  async editRegisterModel(
    field: string,
    raw: string,
    cfg: TbEditTarget = this.config
  ): Promise<void> {
    if (!cfg.configUri) {
      return;
    }
    const fields: ops.RegisterModelField[] = [
      "package",
      "block",
      "map",
      "bus_agent",
      "adapter",
      "use_predictor",
      "reg_test",
      "csr_tests",
      "coverage",
      "backdoor_root",
      "reg_test_door",
      "frontdoor",
    ];
    if (!fields.includes(field as ops.RegisterModelField)) {
      return;
    }
    const f = field as ops.RegisterModelField;
    let value: string | boolean | string[] | undefined;
    if (f === "csr_tests") {
      value = raw ? raw.split(",").filter(Boolean) : [];
    } else if (f === "use_predictor" || f === "reg_test" || f === "coverage") {
      value = raw === "true";
    } else {
      value = raw === "" ? undefined : raw;
    }
    try {
      if (await cfg.apply((t) => ops.setRegisterModelField(t, f, value))) {
        this.log.appendLine(`[actions] editRegisterModel ${field} = ${raw || "(reset)"}`);
      }
    } catch (e) {
      // the required fields refuse to be emptied rather than corrupting the block
      void vscode.window.showWarningMessage(
        vscode.l10n.t("QuickUVM Architect: {0}", (e as Error).message)
      );
    }
  }

  /** Adds/removes the `regress:` block (its presence generates the `Makefile`).
   *  Removing it also strips every `tests[].seeds` — QuickUVM rejects seeds without
   *  a regress block, so the op cascades and the user is told. */
  async toggleRegress(on: boolean, cfg: TbEditTarget = this.config): Promise<void> {
    if (!cfg.configUri) {
      return this.warnNoConfig();
    }
    if (on) {
      if (await cfg.apply((t) => ops.addRegress(t))) {
        this.log.appendLine("[actions] addRegress");
      }
      return;
    }
    const seeded = (cfg.current.tests ?? []).filter(
      (t) => (t as { seeds?: number }).seeds !== undefined
    ).length;
    if (seeded > 0) {
      const go = await vscode.window.showWarningMessage(
        vscode.l10n.t(
          "Remove the regression block? {0} test(s) set `seeds`, which QuickUVM refuses without it — those seed counts are removed too.",
          seeded
        ),
        { modal: true },
        vscode.l10n.t("Remove")
      );
      if (!go) {
        return;
      }
    }
    if (await cfg.apply((t) => ops.removeRegress(t))) {
      this.log.appendLine(`[actions] removeRegress (+${seeded} seeds)`);
    }
  }

  /** Edits one `regress:` field from the settings panel; empty ⇒ default. */
  async editRegress(
    field: string,
    raw: string,
    cfg: TbEditTarget = this.config
  ): Promise<void> {
    if (!cfg.configUri) {
      return;
    }
    const fields: ops.RegressField[] = ["simulator", "filelist", "seeds", "coverage"];
    if (!fields.includes(field as ops.RegressField)) {
      return;
    }
    const f = field as ops.RegressField;
    let value: string | number | boolean | undefined;
    if (raw === "") {
      value = undefined;
    } else if (f === "seeds") {
      const n = Number(raw);
      if (!Number.isInteger(n) || n < 1) {
        return;
      }
      value = n;
    } else if (f === "coverage") {
      value = raw === "true";
    } else {
      value = raw;
    }
    if (await cfg.apply((t) => ops.setRegressField(t, f, value))) {
      this.log.appendLine(`[actions] editRegress ${field} = ${raw || "(reset)"}`);
    }
  }

  /**
   * Edits a field of an agent (docs/07 line 3, P1) — the inspector's property rows.
   * Empty ⇒ resets to the QuickUVM default (`setAgentField` deletes the key and
   * cascades the deletions the validators demand). `active` deliberately does NOT
   * pass through here: it keeps `setAgentActive`, shared with the connection wiring.
   */
  async editAgent(
    name: string,
    field: string,
    raw: string,
    cfg: TbEditTarget = this.config
  ): Promise<void> {
    if (!cfg.configUri || !name) {
      return;
    }
    if (field === "active") {
      // one path for `active` (the H1 wiring uses it too) — raw is "true"/"false"
      if (await cfg.apply((t) => ops.setAgentActive(t, name, raw === "true"))) {
        this.log.appendLine(`[actions] editAgent ${name}.active = ${raw}`);
      }
      return;
    }
    const fields: ops.AgentField[] = [
      "seq_item_style",
      "mode",
      "respond",
      "request_valid",
      "request_ready",
      "reorder_by",
      "reorder_policy",
      "proactive",
      "replicas",
      "clock",
      "reset",
    ];
    if (!fields.includes(field as ops.AgentField)) {
      return;
    }
    const f = field as ops.AgentField;
    let value: string | number | boolean | undefined;
    if (raw === "") {
      value = undefined;
    } else if (f === "replicas") {
      // replica count: integer >= 1 (the input has min=1)
      const n = Number(raw);
      if (!Number.isInteger(n) || n < 1) {
        return;
      }
      value = n;
    } else if (f === "proactive") {
      value = raw === "true";
    } else {
      value = raw;
    }
    if (await cfg.apply((t) => ops.setAgentField(t, name, f, value))) {
      this.log.appendLine(`[actions] editAgent ${name}.${field} = ${raw || "(reset)"}`);
    }
  }

  /**
   * Edits a field of a scoreboard (slice 2). The value comes from the inspector
   * (inline editing), empty => resets to default (match=in_order, field deleted
   * — see `setScoreboardField`). `max_latency` is converted to a number.
   */
  async editScoreboard(
    name: string,
    field: string,
    raw: string,
    cfg: TbEditTarget = this.config
  ): Promise<void> {
    if (!cfg.configUri || !name) {
      return;
    }
    const fields: ops.ScoreboardField[] = [
      "source",
      "monitor",
      "match",
      "match_key",
      "max_latency",
      "window.boundary",
      "window.length",
      "reference_model.language",
    ];
    if (!fields.includes(field as ops.ScoreboardField)) {
      return;
    }
    const f = field as ops.ScoreboardField;
    let value: string | number | undefined;
    if (raw === "") {
      value = undefined;
    } else if (f === "max_latency" || f === "window.length") {
      // cycles / samples per window: an integer, >= 1 for a window (>= 0 for latency)
      const n = Number(raw);
      if (!Number.isInteger(n) || n < (f === "window.length" ? 1 : 0)) {
        return;
      }
      value = n;
    } else {
      value = raw;
    }
    try {
      if (await cfg.apply((t) => ops.setScoreboardField(t, name, f, value))) {
        this.log.appendLine(`[actions] editScoreboard ${name}.${field} = ${raw || "(reset)"}`);
      }
    } catch (e) {
      // e.g. a window on a two-stream scoreboard — refused rather than written
      void vscode.window.showWarningMessage(
        vscode.l10n.t("QuickUVM Architect: {0}", (e as Error).message)
      );
    }
  }

  /**
   * Whitebox probe (K2, slice 3) from a net selected in the schematic view:
   * the XMR path (relative to the DUT instance) and the width come from the MODEL through
   * `proposeProbe` (src/probe.ts, pure and tested); the name is confirmed by the
   * user. The refusals (subsystem bench, unpacked array, interface,
   * port already mapped on an agent) also come from there, with the reason displayed as such.
   */
  async createProbe(viewId: string | undefined, net: string): Promise<void> {
    if (!this.config.configUri) {
      return this.warnNoConfig();
    }
    const model = this.getModel();
    if (!model || !viewId || !net) {
      void vscode.window.showWarningMessage(
        vscode.l10n.t(
          "QuickUVM Architect: select a net in the schematic view first."
        )
      );
      return;
    }
    const check = proposeProbe(model, this.config.current, viewId, net);
    if (!check.ok) {
      void vscode.window.showWarningMessage(
        vscode.l10n.t("QuickUVM Architect: {0}", check.reason)
      );
      return;
    }
    const p = check.proposal;

    // The width: derived from the model when possible. When NOT (all endpoints go
    // through select/concat), we ask for it explicitly — left as default, QuickUVM makes
    // a 1-bit probe and silently TRUNCATES a wide signal.
    let width = p.width ?? undefined;
    if (width === undefined) {
      const raw = await vscode.window.showInputBox({
        title: vscode.l10n.t("Probe width (bits)"),
        value: "1",
        prompt: vscode.l10n.t(
          "the model cannot derive this net's width (its endpoints all go through select/concat) — left unset, QuickUVM would make it 1 bit and truncate"
        ),
        validateInput: (v) =>
          /^[1-9]\d*$/.test(v)
            ? undefined
            : vscode.l10n.t("a positive integer"),
      });
      if (!raw) {
        return;
      }
      width = Number(raw);
    }

    const taken = new Set(p.taken);
    const name = await vscode.window.showInputBox({
      title: vscode.l10n.t("Probe name"),
      value: Actions.uniqueName(p.name, taken),
      prompt: vscode.l10n.t("XMR path, relative to the DUT instance: {0}", p.path),
      validateInput: (v) =>
        !SV_IDENT_RE.test(v)
          ? vscode.l10n.t("invalid SystemVerilog identifier")
          : taken.has(v)
            ? vscode.l10n.t(
                "the name collides with another probe, an agent port/interface, the clock or the reset"
              )
            : undefined,
    });
    if (!name) {
      return;
    }

    // Probe kind: observe-only, functional coverage, or real-valued. Coverage =>
    // `<dut>_probe_monitor` in the env (the packaged anti-bug gate K2 #1 lives in
    // probe.ts). `real` is SVA-only (no coverage, schema §1.8), so the three are
    // mutually exclusive; the real option is offered alongside the coverage pick.
    let coverage = false;
    let real = false;
    if (probeCoverageAllowed(this.config.current)) {
      const NO = vscode.l10n.t("$(eye) Observe only");
      const YES = vscode.l10n.t("$(graph) Also collect functional coverage");
      const REAL = vscode.l10n.t("$(pulse) Real-valued (SVA-only, no coverage)");
      const pick = await vscode.window.showQuickPick([NO, YES, REAL], {
        title: vscode.l10n.t("Probe: functional coverage"),
      });
      if (!pick) {
        return;
      }
      coverage = pick === YES;
      real = pick === REAL;
    }

    // Multi-clock benches: a probe must name the sampling domain (schema §1.8 —
    // this is what lifted the old >1-domain refusal). Single-clock => undefined,
    // so the key is omitted and the common path stays byte-identical.
    let clock: string | undefined;
    const clockDomains = Actions.clockDomainNames(this.config.current);
    if (clockDomains.length > 1) {
      const pick = await vscode.window.showQuickPick(clockDomains, {
        title: vscode.l10n.t("Probe: sampling clock domain"),
      });
      if (!pick) {
        return;
      }
      clock = pick;
    }

    const w = width;
    if (
      await this.config.apply((t) =>
        ops.addProbe(t, { name, path: p.path, width: w, coverage, real, clock })
      )
    ) {
      this.log.appendLine(
        `[actions] createProbe ${name} -> ${p.path} (${w}b${coverage ? ", coverage" : ""}${real ? ", real" : ""}${clock ? `, @${clock}` : ""})`
      );
      if (await this.isComposedChild()) {
        void vscode.window.showWarningMessage(
          vscode.l10n.t(
            "QuickUVM Architect: this config is composed as a subenv of another bench. QuickUVM 0.9.2 generates the probe files but never wires them into the subsystem testbench — the probe only works when this block is generated standalone."
          )
        );
      }
    }
  }

  /**
   * Is the active config referenced as `subenvs[].config` by another? Its probes would
   * be generated, but NOT wired into the subsystem's tb_top (no probe_if
   * instance, no XMR, no config_db, and not even in the filelist) — a real bug
   * of quick-uvm 0.9.2, which nevertheless exits with 0: SILENT failure, so we warn.
   */
  private async isComposedChild(): Promise<boolean> {
    const uri = this.config.configUri;
    if (!uri) {
      return false;
    }
    const found = await vscode.workspace.findFiles(
      "**/*.quickuvm.yaml",
      "**/node_modules/**"
    );
    const files = await Promise.all(
      found.map(async (u) => ({
        path: u.fsPath,
        text: Buffer.from(await vscode.workspace.fs.readFile(u)).toString("utf8"),
      }))
    );
    // the pure predicate (yamlops, tested) compares the paths normalized — includes()
    // on the raw fsPath misses the match on case differences on Windows
    return ops.isComposedChild(files, uri.fsPath);
  }

  /**
   * Derives the inter-block H1 connections from the nets of the subsystem's
   * schematic view and writes them into `connections` (slice 3, "derived composition").
   * Only for the current subsystem (config with `subenvs`, dut = the view's module).
   * The DESTINATION blocks must have a PASSIVE agent (`active: false`) — a
   * quick-uvm constraint; it is WARNED (the child configs are not edited silently,
   * as they are separate files owned by the user).
   */
  async wireConnections(viewId: string | undefined): Promise<void> {
    if (!this.config.configUri) {
      return this.warnNoConfig();
    }
    const model = this.getModel();
    const r = this.resolve(viewId);
    if (!model || !r) {
      return;
    }
    const cfg = this.config.current;
    if (cfg.dut?.name !== r.inst.module) {
      void vscode.window.showWarningMessage(
        vscode.l10n.t(
          "QuickUVM Architect: open the schematic of the subsystem DUT to wire its connections."
        )
      );
      return;
    }
    const subenvs = cfg.subenvs ?? [];
    if (!subenvs.length) {
      void vscode.window.showInformationMessage(
        vscode.l10n.t(
          "QuickUVM Architect: compose blocks as subenvs first (Create subenv)."
        )
      );
      return;
    }
    // child-rel -> subenv name, excluding the ambiguous names: the pure core
    // subenvMapping (compose.ts, tested) — invariant #3 of the composition
    const mapping = subenvMapping(
      model,
      r.inst.path,
      subenvs.map((s) => s.name)
    );
    const derived = deriveConnections(model, r.inst.path, mapping.subenvOf);
    if (mapping.ambiguous.length) {
      derived.warnings.push(
        `ambiguous subenv names, not wired: ${mapping.ambiguous.join(", ")}`
      );
    }
    if (derived.connections.length === 0) {
      const msg = derived.warnings.length
        ? derived.warnings.join("; ")
        : vscode.l10n.t("no inter-block connections found among the composed blocks.");
      void vscode.window.showInformationMessage(
        vscode.l10n.t("QuickUVM Architect: {0}", msg)
      );
      return;
    }
    // ATOMIC edit (a single undo) on MULTIPLE files: `connections` on the top +
    // the DESTINATION block's agent set passive in each child config (an input
    // port driven by a wire cannot also be driven by its own agent — quick-uvm
    // refuses otherwise). The child configs are separate files; we edit them
    // explicitly (not through ConfigService.apply, which touches only the active config).
    // The host only READS the files; the new texts come from planWireEdits
    // (compose.ts, pure, tested — including the folding on a shared file, #4).
    const topUri = this.config.configUri;
    const dir = vscode.Uri.joinPath(topUri, "..");
    const fullRange = (d: vscode.TextDocument): vscode.Range =>
      new vscode.Range(d.positionAt(0), d.positionAt(d.getText().length));

    const topDoc = await vscode.workspace.openTextDocument(topUri);
    const topOld = topDoc.getText();
    const children = new Map<string, { key: string; text: string }>();
    const childDocs = new Map<string, vscode.TextDocument>();
    for (const sink of derived.sinks) {
      const config = subenvs.find((s) => s.name === sink)?.config;
      if (!config || children.has(config)) {
        continue;
      }
      const childUri = vscode.Uri.joinPath(dir, config);
      try {
        const doc = await vscode.workspace.openTextDocument(childUri);
        children.set(config, { key: childUri.toString(), text: doc.getText() });
        childDocs.set(childUri.toString(), doc);
      } catch {
        // missing/unreadable file: the planner puts it under `manual`
      }
    }
    const plan = planWireEdits(topOld, subenvs, derived, children);
    const { passivated, manual } = plan;

    const edit = new vscode.WorkspaceEdit();
    if (plan.topText !== topOld) {
      edit.replace(topUri, fullRange(topDoc), plan.topText);
    }
    for (const [key, text] of plan.childTexts) {
      const doc = childDocs.get(key);
      if (doc) {
        edit.replace(doc.uri, fullRange(doc), text);
      }
    }

    if (!(await vscode.workspace.applyEdit(edit))) {
      void vscode.window.showErrorMessage(
        vscode.l10n.t("QuickUVM Architect: could not write the connections.")
      );
      return;
    }
    await this.config.refresh(); // synchronous: `current` immediately reflects the new YAML

    const parts = [
      vscode.l10n.t("{0} connection(s) wired", derived.connections.length),
    ];
    if (passivated.length) {
      parts.push(
        vscode.l10n.t("agents set passive: {0}", passivated.join(", "))
      );
    }
    if (manual.length) {
      // the child's skeleton has no agent yet (createSubenv does not create one) or
      // the config is missing: the user configures the agent and makes it passive
      parts.push(
        vscode.l10n.t(
          "configure and passivate the agent for: {0}",
          manual.join(", ")
        )
      );
    }
    for (const w of derived.warnings) {
      parts.push(w);
    }
    void vscode.window.showInformationMessage(
      `QuickUVM Architect: ${parts.join(" — ")}`
    );
    this.log.appendLine(
      `[actions] wireConnections: ${derived.connections.length} conn, ` +
        `${passivated.length} passivated, ${manual.length} manual` +
        (derived.warnings.length ? `, ${derived.warnings.length} warnings` : "")
    );
  }

  /**
   * "Compose into parent bench" (slice 3): from a BLOCK's view, composes the block
   * + its block SIBLINGS into the immediate PARENT bench. It reduces to `createSubenv`
   * targeting the parent (recursive ensureDut + skeleton + subenvs). A subsystem requires
   * ≥2 subenvs (quick-uvm), so all the parent's block children are composed;
   * the user confirms the list in createSubenv's QuickPick.
   */
  async composeIntoParent(viewId: string | undefined): Promise<void> {
    const model = this.getModel();
    if (!model || !viewId) {
      return;
    }
    const pc = parentComposition(model, viewId);
    if (!pc) {
      void vscode.window.showInformationMessage(
        vscode.l10n.t(
          "QuickUVM Architect: this is a top-level module — it has no parent bench."
        )
      );
      return;
    }
    if (pc.childRels.length < 2) {
      // quick-uvm constraint: a subsystem composes >=2 subenvs
      const parentModule =
        model.instances.find((i) => i.path === pc.parentPath)?.module ?? "?";
      void vscode.window.showWarningMessage(
        vscode.l10n.t(
          'QuickUVM Architect: the parent bench "{0}" has only {1} composable block(s) — a subsystem needs at least 2 subenvs.',
          parentModule,
          pc.childRels.length
        )
      );
      return;
    }
    // delegates to createSubenv, TARGETING the parent (ensureDut + skeleton + subenvs);
    // the user confirms the list of children in createSubenv's QuickPick
    await this.createSubenv(pc.parentPath, pc.childRels);
  }

  /**
   * Drill into the composed block (docs/05): opens the config file `configRel`
   * (the path from `subenvs[].config`, carried by the drill) with the DEFAULT editor of
   * `*.quickuvm.yaml` — i.e. the per-file TB diagram (slice 4). The path comes from
   * the block actually clicked, so duplicate names open distinct files.
   * The resolution mimics quick-uvm (pathlib): an ABSOLUTE path is taken as-is,
   * only the relative one is bound to the current config's directory. It works on
   * any TbEditTarget: the active config (panel) or the open document
   * (the per-file editor — H1 nesting across levels).
   */
  async openSubenvConfig(
    configRel: string,
    cfg: TbEditTarget = this.config
  ): Promise<void> {
    const uri = cfg.configUri;
    if (!uri || !configRel) {
      return;
    }
    // absolute path: do NOT append it as relative (Uri.joinPath would produce a
    // broken path — `/c:/proj/C:/abs/x.yaml`; quick-uvm accepts it as-is)
    const child = path.isAbsolute(configRel)
      ? vscode.Uri.file(configRel)
      : vscode.Uri.joinPath(uri, "..", configRel);
    try {
      // the default editor of *.quickuvm.yaml is QuvmConfigEditor (slice 4)
      await vscode.commands.executeCommand("vscode.open", child);
    } catch {
      void vscode.window.showWarningMessage(
        vscode.l10n.t('QuickUVM Architect: cannot open "{0}".', configRel)
      );
    }
  }

  private warnNoConfig(): void {
    void vscode.window.showWarningMessage(
      vscode.l10n.t('QuickUVM Architect: no configuration exists yet — use "Set as DUT".')
    );
  }

  private warnNoAgents(): void {
    void vscode.window.showWarningMessage(
      vscode.l10n.t("QuickUVM Architect: the active configuration has no agents yet.")
    );
  }

  /**
   * Active config with dut == the view's module — the subenvs' requirement (docs/03).
   * Without any config: the Set as DUT flow (checkDut). Active config on a DIFFERENT
   * dut: the recursive flow directly from the gesture — an explicit offer of a config
   * dedicated to the block, then Set as DUT on it; no dead button.
   */
  private async ensureDutForView(inst: Instance): Promise<boolean> {
    const dut = this.config.current.dut?.name;
    if (dut === inst.module) {
      return true;
    }
    if (!dut) {
      return this.checkDut(inst);
    }
    const create = vscode.l10n.t(
      "Create {0}.quickuvm.yaml and set its DUT",
      inst.module
    );
    const pick = await vscode.window.showInformationMessage(
      vscode.l10n.t(
        'Agents and subenvs for "{0}" belong to its own config, but the active config targets "{1}" (recursive flow, docs/03).',
        inst.module,
        dut
      ),
      create
    );
    if (pick !== create) {
      return false;
    }
    if (!(await this.config.createConfigFor(inst.module))) {
      return false;
    }
    // the new config is active and without a dut: the standard flow, without the
    // overwrite question (activeDut is now undefined)
    await this.setDut(inst.path);
    return this.config.current.dut?.name === inst.module;
  }

  // ------------------------------------------------------- ignorePorts

  async ignorePorts(pinIds: string[], ignore: boolean): Promise<void> {
    const names = pinIds.map((id) => id.replace(/^<port>\./, ""));
    if (names.length === 0) {
      return;
    }
    await this.config.apply((t) =>
      ignore ? ops.ignorePorts(t, names) : ops.unignorePorts(t, names)
    );
  }

  async fixPortWidth(agent: string, port: string, width: number): Promise<void> {
    await this.config.apply((t) => ops.setAgentPortWidth(t, agent, port, width));
  }

  // ------------------------------------------------------------ intern

  /** The agent actions require a DUT that is set and matches the current view. */
  private async checkDut(inst: Instance): Promise<boolean> {
    const dut = this.config.current.dut?.name;
    if (!dut) {
      const pick = await vscode.window.showInformationMessage(
        vscode.l10n.t("QuickUVM Architect: no DUT is configured yet."),
        vscode.l10n.t("Set this module as DUT")
      );
      if (pick) {
        await this.setDut(inst.path);
        return Boolean(this.config.current.dut?.name);
      }
      return false;
    }
    if (dut !== inst.module) {
      void vscode.window.showWarningMessage(
        vscode.l10n.t(
          "QuickUVM Architect: the configured DUT is \"{0}\", but the current view shows \"{1}\". Open the DUT view or change the DUT.",
          dut,
          inst.module
        )
      );
      return false;
    }
    return true;
  }

  private async askAgentName(suggestion: string): Promise<string | undefined> {
    const existing = new Set(
      (this.config.current.agents ?? []).map((a) => a.name)
    );
    return vscode.window.showInputBox({
      title: vscode.l10n.t("Agent name"),
      value: suggestion,
      prompt: vscode.l10n.t(
        "SystemVerilog identifier; prefixes the generated files"
      ),
      validateInput: (v) =>
        !SV_IDENT_RE.test(v)
          ? vscode.l10n.t("invalid SystemVerilog identifier")
          : existing.has(v)
            ? vscode.l10n.t("an agent with this name already exists")
            : undefined,
    });
  }

  /** The interface instance connected to the given port, through the parent's view. */
  private connectedIface(
    model: ProjectModel,
    inst: Instance,
    portName: string,
    ifaceModule: string
  ): Instance | undefined {
    // the parent = the longest instance path that is a proper prefix of the current path
    let parent: Instance | undefined;
    for (const i of model.instances) {
      if (
        inst.path.startsWith(i.path + ".") &&
        (!parent || i.path.length > parent.path.length)
      ) {
        parent = i;
      }
    }
    if (parent) {
      const rel = inst.path.slice(parent.path.length + 1);
      const view = model.views[parent.path];
      const pin = view?.pins.find((p) => p.pin === `${rel}.${portName}`);
      if (pin?.conn && pin.conn.kind === "iface") {
        const base = pin.conn.ref.split(".")[0];
        const found = model.instances.find(
          (i) => i.path === `${parent.path}.${base}`
        );
        if (found?.iface) {
          return found;
        }
      }
    }
    // fallback: the sole instance of that interface type in the design
    const candidates = model.instances.filter(
      (i) => i.module === ifaceModule && i.iface
    );
    return candidates.length === 1 ? candidates[0] : undefined;
  }
}

/** `g_ch[0..2].u_ch` -> the member paths; an id without a fold stays as-is. */
function expandFold(rel: string): string[] {
  const m = /\[(\d+)\.\.(\d+)\]/.exec(rel);
  if (!m) {
    return [rel];
  }
  const out: string[] = [];
  for (let i = Number(m[1]); i <= Number(m[2]); i++) {
    out.push(rel.replace(m[0], `[${i}]`));
  }
  return out;
}

/** the heuristic dut of a child block (the skeleton from createSubenv, docs/03) */
function heuristicDut(module: string, def: ModuleDef | undefined): ops.DutSpec {
  const oneBitIns = (def?.ports ?? []).filter(
    (p) => p.dir === "in" && p.width === 1
  );
  const clock = oneBitIns.find((p) => CLOCK_RE.test(p.name))?.name ?? null;
  const reset = oneBitIns.find((p) => RESET_RE.test(p.name))?.name ?? null;
  return {
    module,
    clock,
    reset,
    resetActiveLow: reset ? ACTIVE_LOW_RE.test(reset) : true,
    externalReset: false,
    combinational: !clock,
  };
}

/** Agent name suggestion from the common prefix of the selected pins. */
export function suggestName(pinNames: string[]): string {
  const names = pinNames.map((n) => n.replace(/^<port>\./, ""));
  if (names.length === 1) {
    return names[0];
  }
  const first = names[0] ?? "agent";
  let prefix = first;
  for (const n of names) {
    while (prefix && !n.startsWith(prefix)) {
      prefix = prefix.slice(0, -1);
    }
  }
  prefix = prefix.replace(/_+$/, "");
  return SV_IDENT_RE.test(prefix) ? prefix : "agent1";
}
